package com.merits.modules.base.site.servlets.definitions;

//IMPORTS --------------------------------------------------------------------

import com.weezzi.core.servlets.base.WeezziServletAction;

/**
 * <b>Title: </b> General Servlet Actions<br/>
 * <b>Description: </b> General Servlet Actions<br/>
 *
 * @author Auto-generated by Weezzi Site Builder
 * @version 1.0
 */
public enum GeneralServletAjaxActions implements WeezziServletAction {


	// ENUMERATIONS -----------------------------------------------------------

    ChangeLanguage("changelanguage"),
    CancelPaymentCode("cancelpaymentcode"),
    SelectShop("selectshop"),
    AddCashier("addcashier"),
    ValidateCode("validatecode"),
    RequestPayment("requestpayment"),
    VolunteerAcceptPayment("volunteeracceptpayment"),
    VolunteerRefusePayment("volunteerrefusepayment"),
    Contact("contact"),
    Logout("logout"),
;


    // PROPERTIES -------------------------------------------------------------

    
    private String urlPrefix;
    
    
    // CONSTRUCTOR ------------------------------------------------------------
    
    
    GeneralServletAjaxActions(String urlPrefix) {
    	this.urlPrefix = urlPrefix;
    }

    
	// METHODS ----------------------------------------------------------------
	
	
	public String getName() {
		// Local Variables
		return name();
	}


	/**
	 * Gets urlPrefix
	 * @return the urlPrefix
	 */
	public String getUrlPrefix() {
		return urlPrefix;
	}


}