package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import com.weezzi.core.data.*;
import com.weezzi.core.dbmanager.dao.BulkDAO;
import com.weezzi.core.dbmanager.dao.DAOParameters;
import com.weezzi.utils.extras.cache.WeezziCacheObjectType;
import com.merits.modules.base.dao.ShopTransactionsGoodsDAO;

import java.util.Vector;
import java.sql.ResultSet;
import java.util.Collection;


/**
 * <b>Title: </b>Shop Transactions Good Bulk Data Transfer Object<br/>
 * <b>Description: </b>Shop Transactions Good Bulk DTO Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
@SuppressWarnings("unused")
public class BulkShopTransactionsGoodsDAO extends BulkDAO {


	// CONSTANTS ---------------------------------------------------------------

	
	public static final String CACHE_PREFIX = "B11#";
	private static final long serialVersionUID = 1L;


    // DATA TYPE ENUMERATION --------------------------------------------------


    /**
     *  DAO Search Type
     */
    public enum SearchType {

    	// Single Record Queries

		;
    	
        private String cachePrefix;
        
        SearchType(String cachePrefix) {
        	this.cachePrefix = cachePrefix;
        }

        /**
         * Gets cache prefix
         **/
        public String toString() {
        	return cachePrefix;
        }
    }


    // PROPERTIES --------------------------------------------------------------


    // Shop Transactions Good Bulk DTO Data Vector
    public Vector<ShopTransactionsGoodsDAO> data;


    // CONSTRUCTORS ------------------------------------------------------------


    /**
     * Bulk DTO Search Constructor
     * @param type Type Bulk DAO Query Type
     */
    public BulkShopTransactionsGoodsDAO(SearchType searchType) {
        // Set Cache Object Type
        this.setCacheObjectType(WeezziCacheObjectType.Query);
        // Set Bulk DAO search type
        this.setSearchType(searchType);
        this.data = new Vector<ShopTransactionsGoodsDAO>();
    }


    // PUBLIC ------------------------------------------------------------------


    /**
     * Adds a Shop Transactions Good DAO to the data
     * @param shopTransactionsGoods ShopTransactionsGoodsDAO Shop Transactions Good DAO
     */
    public void add(ShopTransactionsGoodsDAO shopTransactionsGoods) {
        // Adds Shop Transactions Good
        data.add(shopTransactionsGoods);
    }


    /**
     * Adds a Shop Transactions Good from a recordset
     * @param rs ResultSet
     * @throws Exception
     */
    public void add(ResultSet rs) throws Exception {
    	// Local Variables
    	ShopTransactionsGoodsDAO dto;
    	// Create DTO
    	dto = new ShopTransactionsGoodsDAO();
    	// Fill DTO values
    	dto.fillValuesFromResultSet(rs);
        this.add(dto);
    }


    /**
     * Adds a collection of Shop Transactions Good DTO to the list
     * @param Collection Shop Transactions Good DTO Collection
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
    public void add(Collection collection) {
        // Adds all collection data
        data.addAll(collection);
    }


    // GETTERS -----------------------------------------------------------------


    /**
     * Gets all Bulk DTO Data
     * @return Vector
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
    public Vector getAllData() {
        return data;
    }


    /**
     * Gets a particular Shop Transactions Good DTO
     * @param index int Shop Transactions Good index
     * @return ShopTransactionsGoodsDAO Shop Transactions Good data transfer data object
     */
    public ShopTransactionsGoodsDAO get(int index) {
        // Gets one Shop Transactions Good from the bulk data
        return data.get(index);
    }


    /**
     * Gets all data as an array
     * @return ShopTransactionsGoodsDAO[] Shop Transactions Good DTO array
     */
    public ShopTransactionsGoodsDAO[] getArray() {
        // Local variables
        ShopTransactionsGoodsDAO[] array = new ShopTransactionsGoodsDAO[data.size()];
        // Fill Array
        for (int i=0; i<data.size(); i++) {
            // Fill array value
            array[i] = this.get(i);
        }
        // Return array
        return array;
    }


    /**
     * Gets bulk set data size
     * @return int
     */
    public int getBulkSize() {
        return data.size();
    }


    /**
     * Resets all data in the Bulk DTO
     */
    public void reset() {
        data.clear();
    }


    // CACHING ----------------------------------------------------------------
    
    
	/**
	 * Gets cachePrefix
	 * @return The cachePrefix of this object
	 */
	public String getCachePrefix() {
		return CACHE_PREFIX;
	}


    // DATABASE MANAGER SPECIFIC ----------------------------------------------

    
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
    public String getDBConnectionName() {
    	return "Merits_Merits";
    }

    
    // ------------------------------------------------------------------------
    // PARAMETERS CLASSES -----------------------------------------------------
    // ------------------------------------------------------------------------




}
