package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import com.weezzi.core.dbmanager.dao.BulkDAO;
import com.weezzi.core.dbmanager.dao.DAOParameters;
import com.weezzi.utils.extras.cache.WeezziCacheObjectType;
import com.merits.modules.base.dao.WalletRecordsMasterWalletSPQ;

import java.util.Vector;
import java.sql.ResultSet;
import java.util.Collection;


/**
 * <b>Title: </b>Wallet Record Bulk Data Transfer Object<br/>
 * <b>Description: </b>Wallet Record Bulk DTO Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */

public class BulkWalletRecordsMasterWalletSPQ extends BulkDAO {


	// CONSTANTS ---------------------------------------------------------------

	
	public static final String CACHE_PREFIX = "BS1_2#";
	private static final long serialVersionUID = 1L;


    // PROPERTIES --------------------------------------------------------------


    // Wallet Record Bulk DTO Data Vector
    public Vector<WalletRecordsMasterWalletSPQ> data;


    // CONSTRUCTORS ------------------------------------------------------------


    /**
     * Bulk DAO Special Query Constructor
     * @param idWallet Object Wallet Records Wallet Identifier RelationShip Field
     * @param refWallet Object Wallet Records Ref Wallet RelationShip Field
     */
    public BulkWalletRecordsMasterWalletSPQ() {
        // Set Cache Object Type
        this.setCacheObjectType(WeezziCacheObjectType.SpecialQuery);
        this.data = new Vector<WalletRecordsMasterWalletSPQ>();
        this.setBlockSize(100);
    }


    // PUBLIC ------------------------------------------------------------------


    /**
     * Adds a Wallet Record DAO to the data
     * @param walletRecords WalletRecordsMasterWalletSPQ Wallet Record DAO
     */
    public void add(WalletRecordsMasterWalletSPQ walletRecords) {
        // Adds Wallet Record
        data.add(walletRecords);
    }


    /**
     * Adds a Wallet Record from a recordset
     * @param rs ResultSet
     * @throws Exception
     */
    public void add(ResultSet rs) throws Exception {
    	// Local Variables
    	WalletRecordsMasterWalletSPQ dto;
    	// Create DTO
    	dto = new WalletRecordsMasterWalletSPQ();
    	// Fill DTO values
    	dto.fillValuesFromResultSet(rs);
        this.add(dto);
    }


    /**
     * Adds a collection of Wallet Record DTO to the list
     * @param Collection Wallet Record DTO Collection
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
    public void add(Collection collection) {
        // Adds all collection data
        data.addAll(collection);
    }


    // GETTERS -----------------------------------------------------------------


    /**
     * Gets all Bulk DTO Data
     * @return Vector
     */
    @SuppressWarnings("rawtypes")
    public Vector getAllData() {
        return data;
    }


    /**
     * Gets a particular Wallet Record DTO
     * @param index int Wallet Record index
     * @return WalletRecordsMasterWalletSPQ Wallet Record data transfer data object
     */
    public WalletRecordsMasterWalletSPQ get(int index) {
        // Gets one Wallet Record from the bulk data
        return data.get(index);
    }


    /**
     * Gets all data as an array
     * @return WalletRecordsMasterWalletSPQ[] Wallet Record DTO array
     */
    public WalletRecordsMasterWalletSPQ[] getArray() {
        // Local variables
        WalletRecordsMasterWalletSPQ[] array = new WalletRecordsMasterWalletSPQ[data.size()];
        // Fill Array
        for (int i=0; i<data.size(); i++) {
            // Fill array value
            array[i] = this.get(i);
        }
        // Return array
        return array;
    }


    /**
     * Gets bulk set data size
     * @return int
     */
    public int getBulkSize() {
        return data.size();
    }


    /**
     * Resets all data in the Bulk DTO
     */
    public void reset() {
        data.clear();
    }


    // CACHING ----------------------------------------------------------------
    
    
	/**
	 * Gets cachePrefix
	 * @return The cachePrefix of this object
	 */
	public String getCachePrefix() {
		return CACHE_PREFIX;
	}


    // DATABASE MANAGER SPECIFIC ----------------------------------------------

    
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
    public String getDBConnectionName() {
    	return "Merits_Merits";
    }

    
    // ------------------------------------------------------------------------
    // PARAMETERS CLASSES -----------------------------------------------------
    // ------------------------------------------------------------------------




	// MasterWallet Parameters Class -----------------------------------------------


	/**
	 * MasterWallet
	 */
	public class Parameters extends DAOParameters {

		
		// Properties .........................................................

		
        // Wallet Records Identifier
        private long id;
        

		// Constructors .......................................................

		
		public Parameters(long id) {
            this.id = id;
		}


        // DAO Parameters .....................................................


        /**
         * Gets the search fields
         * @return
         */
		public Object[] getSearchFields() {
			// Local Variables
			return new Object[] {id};
		}
	
	
		/**
		 * Gets the object cache keys
		 * @return cacheKeys
		 */
		public String[] getCacheKeys() {
			return null;
		}

		
	}


}
