package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import com.weezzi.core.dbmanager.dao.BulkDAO;
import com.weezzi.core.dbmanager.dao.DAOParameters;
import com.weezzi.utils.extras.cache.WeezziCacheObjectType;
import com.merits.modules.base.dao.ShopGoodtypesShopGoodSPQ;

import java.util.Vector;
import java.sql.ResultSet;
import java.util.Collection;


/**
 * <b>Title: </b>Shop Goodtype Bulk Data Transfer Object<br/>
 * <b>Description: </b>Shop Goodtype Bulk DTO Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */

public class BulkShopGoodtypesShopGoodSPQ extends BulkDAO {


	// CONSTANTS ---------------------------------------------------------------

	
	public static final String CACHE_PREFIX = "BS6_0#";
	private static final long serialVersionUID = 1L;


    // PROPERTIES --------------------------------------------------------------


    // Shop Goodtype Bulk DTO Data Vector
    public Vector<ShopGoodtypesShopGoodSPQ> data;


    // CONSTRUCTORS ------------------------------------------------------------


    /**
     * Bulk DAO Special Query Constructor
     * @param idShop Object Shop Goodtypes Shop Identifier RelationShip Field
     * @param idGoodtype Object Shop Goodtypes Goodtype Identifier RelationShip Field
     */
    public BulkShopGoodtypesShopGoodSPQ() {
        // Set Cache Object Type
        this.setCacheObjectType(WeezziCacheObjectType.SpecialQuery);
        this.data = new Vector<ShopGoodtypesShopGoodSPQ>();
        this.setBlockSize(100);
    }


    // PUBLIC ------------------------------------------------------------------


    /**
     * Adds a Shop Goodtype DAO to the data
     * @param shopGoodtypes ShopGoodtypesShopGoodSPQ Shop Goodtype DAO
     */
    public void add(ShopGoodtypesShopGoodSPQ shopGoodtypes) {
        // Adds Shop Goodtype
        data.add(shopGoodtypes);
    }


    /**
     * Adds a Shop Goodtype from a recordset
     * @param rs ResultSet
     * @throws Exception
     */
    public void add(ResultSet rs) throws Exception {
    	// Local Variables
    	ShopGoodtypesShopGoodSPQ dto;
    	// Create DTO
    	dto = new ShopGoodtypesShopGoodSPQ();
    	// Fill DTO values
    	dto.fillValuesFromResultSet(rs);
        this.add(dto);
    }


    /**
     * Adds a collection of Shop Goodtype DTO to the list
     * @param Collection Shop Goodtype DTO Collection
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
    public void add(Collection collection) {
        // Adds all collection data
        data.addAll(collection);
    }


    // GETTERS -----------------------------------------------------------------


    /**
     * Gets all Bulk DTO Data
     * @return Vector
     */
    @SuppressWarnings("rawtypes")
    public Vector getAllData() {
        return data;
    }


    /**
     * Gets a particular Shop Goodtype DTO
     * @param index int Shop Goodtype index
     * @return ShopGoodtypesShopGoodSPQ Shop Goodtype data transfer data object
     */
    public ShopGoodtypesShopGoodSPQ get(int index) {
        // Gets one Shop Goodtype from the bulk data
        return data.get(index);
    }


    /**
     * Gets all data as an array
     * @return ShopGoodtypesShopGoodSPQ[] Shop Goodtype DTO array
     */
    public ShopGoodtypesShopGoodSPQ[] getArray() {
        // Local variables
        ShopGoodtypesShopGoodSPQ[] array = new ShopGoodtypesShopGoodSPQ[data.size()];
        // Fill Array
        for (int i=0; i<data.size(); i++) {
            // Fill array value
            array[i] = this.get(i);
        }
        // Return array
        return array;
    }


    /**
     * Gets bulk set data size
     * @return int
     */
    public int getBulkSize() {
        return data.size();
    }


    /**
     * Resets all data in the Bulk DTO
     */
    public void reset() {
        data.clear();
    }


    // CACHING ----------------------------------------------------------------
    
    
	/**
	 * Gets cachePrefix
	 * @return The cachePrefix of this object
	 */
	public String getCachePrefix() {
		return CACHE_PREFIX;
	}


    // DATABASE MANAGER SPECIFIC ----------------------------------------------

    
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
    public String getDBConnectionName() {
    	return "Merits_Merits";
    }

    
    // ------------------------------------------------------------------------
    // PARAMETERS CLASSES -----------------------------------------------------
    // ------------------------------------------------------------------------




	// ShopGood Parameters Class -----------------------------------------------


	/**
	 * ShopGood
	 */
	public class Parameters extends DAOParameters {

		
		// Properties .........................................................

		
        // Shop Goodtypes Shop Id
        private long shopId;
        // Shop Goodtypes Lang Code
        private String langCode;
        

		// Constructors .......................................................

		
		public Parameters(long shopId, String langCode) {
            this.shopId = shopId;
            this.langCode = langCode;
		}


        // DAO Parameters .....................................................


        /**
         * Gets the search fields
         * @return
         */
		public Object[] getSearchFields() {
			// Local Variables
			return new Object[] {shopId, langCode};
		}
	
	
		/**
		 * Gets the object cache keys
		 * @return cacheKeys
		 */
		public String[] getCacheKeys() {
			return null;
		}

		
	}


}
