package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import java.sql.CallableStatement;
import java.sql.Timestamp;

import com.weezzi.core.data.*;
import com.weezzi.core.dbmanager.dao.UpdaterDAO;
import com.weezzi.utils.StringUtilities;


/**
 * <b>Title: </b>Company Updater Object<br/>
 * <b>Description: </b>Company Updater Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
 @SuppressWarnings("unused")
public class CompaniesUpdater implements UpdaterDAO {


    // PROPERTIES --------------------------------------------------------------

    private long id;
    private String name;
    private String description;
    private Image photo;
    private String url;
    private EditInfo editInfo;
    private PublishInfo publishInfo;
    private long orderNumber;
    private String langCode;


    // CONSTRUCTORS ------------------------------------------------------------


	/**
	 * Empty Constructor
	 **/
	public CompaniesUpdater(long id, String name, String description, Image photo, String url, PublishInfo publishInfo, String langCode, UpdateInfo updateInfo) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.photo = photo;
        this.url = url;
        this.editInfo = editInfo;
        this.publishInfo = publishInfo;
        this.orderNumber = orderNumber;
        this.langCode = langCode;
	}


	// PUBLIC -----------------------------------------------------------------

	
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
	public String getDBConnectionName() {
		return "Merits_Merits";
	}


	/**
	 * Gets update SQL
	 * @return query
	 */
	public String getQuerySQL() {
		return "UPDATE COMPANIES, `weezziserver`.`MULTILANG_TRANSLATIONS` " +
               " SET NAME = ? , `weezziserver`.MULTILANG_TRANSLATIONS.MEDIUM_TEXT1 = ? , PHOTO = ? , URL = ? , PUBLISH_INFO_DATE  = ? , PUBLISH_INFO_USER  = ? , ORDER_NUMBER = ? , EDIT_INFO_UPDATE_DATE  = ? , EDIT_INFO_UPDATE_USER  = ?  " +
               " WHERE COMPANIES.MLK_ID = `weezziserver`.MULTILANG_TRANSLATIONS.ID_MLK AND `weezziserver`.MULTILANG_TRANSLATIONS.LANG_CODE = ? AND COMPANIES.ID = ?";
	}
	
	
	/**
	 * Updates Query Fields
	 * @param statment
	 * @throws Exception
	 */
	public void updateFields(CallableStatement statement) throws Exception {
        // Set Fields
        statement.setString(1, StringUtilities.capString(name, 100));
        statement.setString(2, description);
        // Check If Null
        if (photo == null) {
            statement.setNull(3, java.sql.Types.VARCHAR);
        } else {
            statement.setString(3, photo.serialize());
        }
        // Check If Null
        if (url == null) {
            statement.setNull(4, java.sql.Types.VARCHAR);
        } else {
            statement.setString(4, StringUtilities.capString(url, 100));
        }
        // Check if edit info create date is Null
        if (editInfo.getCreateDate() == null) {
            statement.setNull(5, java.sql.Types.TIMESTAMP);
        } else {
            // Set create date
            statement.setTimestamp(5,  editInfo.getCreateDate());
        } 
        // Check if edit info create user is Null
        if (editInfo.getCreateUserId() == null) {
            statement.setNull(6, java.sql.Types.NUMERIC);
        } else {
            // Set create user
            statement.setLong(6, editInfo.getCreateUserId());
        } 
        // Check if edit info update date is Null
        if (editInfo.getUpdateDate() == null) {
            statement.setNull(7, java.sql.Types.TIMESTAMP);
        } else {
            // Set update date
            statement.setTimestamp(7,  editInfo.getUpdateDate());
        } 
        // Check if edit info update user is Null
        if (editInfo.getUpdateUserId() == null) {
            statement.setNull(8, java.sql.Types.NUMERIC);
        } else {
            // Set update user
            statement.setLong(8, editInfo.getUpdateUserId());
        } 
        // Check if publish info is null
        if (publishInfo != null) {
            // Check if publish info create date is Null
            if (publishInfo.getPublishDate() == null) {
                statement.setNull(9, java.sql.Types.TIMESTAMP);
            } else {
                // Set publish date
                statement.setTimestamp(9,  publishInfo.getPublishDate());
            } 
            // Check if publish info create user is Null
            if (publishInfo.getPublishUserId() == null) {
                statement.setNull(10, java.sql.Types.NUMERIC);
            } else {
                // Set publish user
                statement.setLong(10, publishInfo.getPublishUserId());
            } 
        } else {
            statement.setNull(9, java.sql.Types.TIMESTAMP);
            statement.setNull(10, java.sql.Types.NUMERIC);
        }
        statement.setLong(11, orderNumber);
        // Set multilang language code
        statement.setString(12, langCode);
        statement.setLong(13, id);
	}


	/**
	 * Gets extended update SQL
	 * @return query
	 */
	public String getExtendedQuerySQL() {
		return " UPDATE COMPANIES SET MLK_LANGS = (" + 
                "SELECT group_concat(lang_code) FROM (SELECT MLK_ID FROM COMPANIES WHERE ID=?) AS TEMP, `weezziserver`.multilang_translations " + 
                "WHERE `weezziserver`.multilang_translations.id_mlk= TEMP.MLK_ID " + 
                    "AND length(`weezziserver`.multilang_translations.MEDIUM_TEXT1) > 0 " + 
                ") WHERE ID = ?";
	}
	
	
	/**
	 * Updates Extended Query Fields
	 * @param statment
	 * @throws Exception
	 */
	public void updateExtendedQueryFields(CallableStatement statement) throws Exception {
        statement.setLong(1, id);
        statement.setLong(2, id);
	}
	
	
}
