package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import com.weezzi.core.data.*;
import com.weezzi.core.dbmanager.dao.SingleRecordDAO;
import com.weezzi.utils.StringUtilities;
import com.weezzi.utils.extras.cache.WeezziCacheObjectType;
import com.weezzi.utils.extras.console.Console;
import com.weezzi.core.dbmanager.dao.DAOParameters;
import com.merits.modules.base.uobjects.enums.PaymentCodeStatus;


import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;



/**
 * <b>Title: </b>Payments Code Data Access Object<br/>
 * <b>Description: </b>Payments Code DAO Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
public class PaymentsCodeDAO extends SingleRecordDAO {


	// CONSTANTS --------------------------------------------------------------

	
	public static final String CACHE_PREFIX = "D9#";
	private static final long serialVersionUID = 1l;


    // MULTI-LANGUAGE ---------------------------------------------------------


    /**
     *  Multi-Language
     */
    public enum MultiLanguageFields {
        ;

        private String column;

        MultiLanguageFields(String column) {
        	this.column = column;
        }

        public String getColumnName() {
        	return column;
        }
	}


    // DATA TYPE ENUMERATION --------------------------------------------------


    /**
     *  DAO Search Type
     */
    public enum SearchType {

    	// Single Record Queries
        GetPaymentCode("Q1"),
        GetLatest("Q2"),

		;
    	
        private String cachePrefix;
        
        SearchType(String cachePrefix) {
        	this.cachePrefix = cachePrefix;
        }

        /**
         * Gets cache prefix
         **/
        public String toString() {
        	return cachePrefix;
        }
    }


    // PROPERTIES --------------------------------------------------------------

    // Payments Code Identifier
    private long id;
    // Payments Code Volunteer Identifier
    private long idVolunteer;
    // Payments Code Create Date
    private Timestamp createDate;
    // Payments Code Expiry Date
    private Timestamp expiryDate;
    // Payments Code Code Status
    private PaymentCodeStatus codeStatus;
    // Payments Code Payment Code
    private String paymentCode;


    // CONSTRUCTORS ------------------------------------------------------------


	/**
	 * Empty Constructor
	 **/
	public PaymentsCodeDAO() {
        // Set cache object type
		this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
	}


	/**
	 * Type Constructor
	 **/
	public PaymentsCodeDAO(SearchType type) {
        // Set DAO Search type
        this.setSearchType(type);
        // Set cache object type
		this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
	}
	
	
    /**
     * Payments Code Bean Field Constructor
     * @param id long Payments Code Identifier
     */
    public PaymentsCodeDAO(long id) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Payments Code Identifier
        setId(id);
    }


    /**
     * Payments Code Bean Field Constructor
     * @param id long Payments Code Identifier
     * @param idVolunteer long Payments Code Volunteer Identifier
     * @param createDate Timestamp Payments Code Create Date
     * @param expiryDate Timestamp Payments Code Expiry Date
     * @param codeStatus PaymentCodeStatus Payments Code Code Status
     */
    public PaymentsCodeDAO(long id, long idVolunteer, Timestamp createDate
                    , Timestamp expiryDate, PaymentCodeStatus codeStatus) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Payments Code Identifier
        setId(id);
        // Set Payments Code Volunteer Identifier
        setIdVolunteer(idVolunteer);
        // Set Payments Code Create Date
        setCreateDate(createDate);
        // Set Payments Code Expiry Date
        setExpiryDate(expiryDate);
        // Set Payments Code Code Status
        setCodeStatus(codeStatus);
    }


    /**
     * Payments Code Bean Field Constructor
     * @param id long Payments Code Identifier
     * @param idVolunteer long Payments Code Volunteer Identifier
     * @param createDate Timestamp Payments Code Create Date
     * @param expiryDate Timestamp Payments Code Expiry Date
     * @param codeStatus PaymentCodeStatus Payments Code Code Status
     * @param paymentCode String Payments Code Payment Code
     */
    public PaymentsCodeDAO(long id, long idVolunteer, Timestamp createDate
                    , Timestamp expiryDate, PaymentCodeStatus codeStatus, String paymentCode) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Payments Code Identifier
        setId(id);
        // Set Payments Code Volunteer Identifier
        setIdVolunteer(idVolunteer);
        // Set Payments Code Create Date
        setCreateDate(createDate);
        // Set Payments Code Expiry Date
        setExpiryDate(expiryDate);
        // Set Payments Code Code Status
        setCodeStatus(codeStatus);
        // Set Payments Code Payment Code
        setPaymentCode(paymentCode);
    }


    

    
    // TYPE -------------------------------------------------------------------

    
    /**
     * Sets DAO search type
     * @param type
     */
    public void setSearchType(SearchType type) {
    	// Sets DAO type
    	super.setSearchType(type);
    }


	// GETTERS -----------------------------------------------------------------


    /**
     * Get Payments Code Identifier
     * @return long Payments Code Identifier
     */
    public long getId() {
        return this.id;
    }


    /**
     * Get Payments Code Volunteer Identifier
     * @return long Payments Code Volunteer Identifier
     */
    public long getIdVolunteer() {
        return this.idVolunteer;
    }


    /**
     * Get Payments Code Create Date
     * @return Timestamp Payments Code Create Date
     */
    public Timestamp getCreateDate() {
        return this.createDate;
    }


    /**
     * Get Payments Code Expiry Date
     * @return Timestamp Payments Code Expiry Date
     */
    public Timestamp getExpiryDate() {
        return this.expiryDate;
    }


    /**
     * Get Payments Code Code Status
     * @return PaymentCodeStatus Payments Code Code Status
     */
    public PaymentCodeStatus getCodeStatus() {
        return this.codeStatus;
    }


    /**
     * Get Payments Code Payment Code
     * @return String Payments Code Payment Code
     */
    public String getPaymentCode() {
        return this.paymentCode;
    }



	// SETTERS -----------------------------------------------------------------


    /**
     * Set Payments Code Identifier
     * @param id long Payments Code Identifier
     */
    public void setId(long id) {
        this.id = id;
    }


    /**
     * Set Payments Code Volunteer Identifier
     * @param idVolunteer long Payments Code Volunteer Identifier
     */
    public void setIdVolunteer(long idVolunteer) {
        this.idVolunteer = idVolunteer;
    }


    /**
     * Set Payments Code Create Date
     * @param createDate Timestamp Payments Code Create Date
     */
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }


    /**
     * Set Payments Code Expiry Date
     * @param expiryDate Timestamp Payments Code Expiry Date
     */
    public void setExpiryDate(Timestamp expiryDate) {
        this.expiryDate = expiryDate;
    }


    /**
     * Set Payments Code Code Status
     * @param codeStatus PaymentCodeStatus Payments Code Code Status
     */
    public void setCodeStatus(PaymentCodeStatus codeStatus) {
        this.codeStatus = codeStatus;
    }


    /**
     * Set Payments Code Payment Code
     * @param paymentCode String Payments Code Payment Code
     */
    public void setPaymentCode(String paymentCode) {
        this.paymentCode = paymentCode;
    }



    // MULTI-LANGUAGE ---------------------------------------------------------



	// DAO ID -----------------------------------------------------------------

    
    /**
     * Checks if has Id Field
     */
    public boolean hasIdField() {
    	return true;
    }

    
    /**
     * Sets Id
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }


    // CACHING ----------------------------------------------------------------
    
    
	/**
	 * Gets cachePrefix
	 * @return The cachePrefix of this object
	 */
	public String getCachePrefix() {
		return CACHE_PREFIX;
	}
	
	
	/**
	 * Gets the object cache keys
	 * @return cacheKeys
	 */
	public String[] getCacheKeys() {
		if (getParameters() != null) {
			return getParameters().getCacheKeys();
		}
		return null;
	}
	

    // DATABASE MANAGER SPECIFIC ----------------------------------------------

    
    /**
     * Gets table name
     */
    public String getTableName() {
    	return "PAYMENTS_CODE";
    }

    
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
    public String getDBConnectionName() {
    	return "Merits_Merits";
    }

    
    /**
     * Gets Insert query SQL
     * @return Insert SQL
     */
    public String getInsertSQL() {
    	// SQL
    	return "INSERT INTO PAYMENTS_CODE (`ID_VOLUNTEER`, `CREATE_DATE`, `EXPIRY_DATE`, `CODE_STATUS`, `PAYMENT_CODE`) values (?, ?, ?, ?, ?)";
    }

    
    /**
     * Gets Insert procedure
     */
    public String getInsertProcedureName() {
    	return "PAYMENTS_CODE_PROC(?, ?, ?, ?, ?, ?)";
    }


	// RESULTSETS & STATEMENTS ------------------------------------------------
	    
    
    /**
     * Fills insert fields
     * @param statement
     */
    public void fillStatementFieldsForInsert(CallableStatement statement) throws Exception {
        // Set Payments Code Volunteer Identifier
        statement.setLong(1, idVolunteer);
        // Set Payments Code Create Date
        statement.setTimestamp(2, createDate);
        // Set Payments Code Expiry Date
        statement.setTimestamp(3, expiryDate);
        // Set Payments Code Code Status
        statement.setInt(4, codeStatus.getValue());
        // Check If Payments Code Payment Code Is Null
        if (paymentCode == null) {
            statement.setNull(5, java.sql.Types.VARCHAR);
        } else {
            // Set Payments Code Payment Code
            statement.setString(5, StringUtilities.capString(paymentCode,10));
        }
    }


    /**
     * Sets DAO values from a resultset 
     * @param resultset
     */
    public void fillValuesFromResultSet(ResultSet resultset) throws Exception {
        // Set Payments Code Identifier
        this.setId(resultset.getLong("ID"));
        // Set Payments Code Volunteer Identifier
        this.setIdVolunteer(resultset.getLong("ID_VOLUNTEER"));
        // Set Payments Code Create Date
        this.setCreateDate(resultset.getTimestamp("CREATE_DATE", SingleRecordDAO.TIMEZONE));
        // Set Payments Code Expiry Date
        this.setExpiryDate(resultset.getTimestamp("EXPIRY_DATE", SingleRecordDAO.TIMEZONE));
        // Set Payments Code Code Status
        this.setCodeStatus(PaymentCodeStatus.getByValue(resultset.getInt("CODE_STATUS")));
        // Set Payments Code Payment Code
        this.setPaymentCode(resultset.getString("PAYMENT_CODE"));
        // Check if was null
        if (resultset.wasNull()) {
            this.setPaymentCode(null);
        }
    }

    
    // ------------------------------------------------------------------------
    // PARAMETERS CLASSES -----------------------------------------------------
    // ------------------------------------------------------------------------



	// GetPaymentCode Parameters Class -----------------------------------------------


	/**
	 * GetPaymentCode
	 */
	public class GetPaymentCodeParameters extends DAOParameters {

		
		// Properties .........................................................

		
        // Payments Code Payment Code
        private String paymentCode;
        

		// Constructors .......................................................

		
		public GetPaymentCodeParameters(String paymentCode) {
            this.paymentCode = paymentCode;
		}


        // DAO Parameters .....................................................


        /**
         * Gets the search fields
         * @return
         */
		public Object[] getSearchFields() {
			// Local Variables
			return new Object[] {paymentCode};
		}
	
	
		/**
		 * Gets the object cache keys
		 * @return cacheKeys
		 */
		public String[] getCacheKeys() {
			return null;
		}

		
	}


	// GetLatest Parameters Class -----------------------------------------------


	/**
	 * GetLatest
	 */
	public class GetLatestParameters extends DAOParameters {

		
		// Properties .........................................................

		
        // Payments Code Volunteer Identifier
        private long idVolunteer;
        

		// Constructors .......................................................

		
		public GetLatestParameters(long idVolunteer) {
            this.idVolunteer = idVolunteer;
		}


        // DAO Parameters .....................................................


        /**
         * Gets the search fields
         * @return
         */
		public Object[] getSearchFields() {
			// Local Variables
			return new Object[] {idVolunteer};
		}
	
	
		/**
		 * Gets the object cache keys
		 * @return cacheKeys
		 */
		public String[] getCacheKeys() {
			return null;
		}

		
	}

}
