package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import com.weezzi.core.data.*;
import com.weezzi.core.dbmanager.dao.SingleRecordDAO;
import com.weezzi.utils.StringUtilities;
import com.weezzi.utils.extras.cache.WeezziCacheObjectType;
import com.weezzi.utils.extras.console.Console;
import com.merits.modules.base.uobjects.enums.PaymentRequestStatus;


import java.sql.CallableStatement;
import java.sql.ResultSet;



/**
 * <b>Title: </b>Payments Request Data Access Object<br/>
 * <b>Description: </b>Payments Request DAO Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
public class PaymentsRequestsDAO extends SingleRecordDAO {


	// CONSTANTS --------------------------------------------------------------

	
	public static final String CACHE_PREFIX = "D10#";
	private static final long serialVersionUID = 1l;


    // MULTI-LANGUAGE ---------------------------------------------------------


    /**
     *  Multi-Language
     */
    public enum MultiLanguageFields {
        ;

        private String column;

        MultiLanguageFields(String column) {
        	this.column = column;
        }

        public String getColumnName() {
        	return column;
        }
	}


    // DATA TYPE ENUMERATION --------------------------------------------------


    /**
     *  DAO Search Type
     */
    public enum SearchType {

    	// Single Record Queries

		;
    	
        private String cachePrefix;
        
        SearchType(String cachePrefix) {
        	this.cachePrefix = cachePrefix;
        }

        /**
         * Gets cache prefix
         **/
        public String toString() {
        	return cachePrefix;
        }
    }


    // PROPERTIES --------------------------------------------------------------

    // Payments Requests Identifier
    private long id;
    // Payments Requests Shop Identifier
    private long idShop;
    // Payments Requests Cashier Identifier
    private long idCashier;
    // Payments Requests Volunteer Identifier
    private long idVolunteer;
    // Payments Requests Payment Code Identifier
    private long idPaymentCode;
    // Payments Requests Transaction Value
    private float transactionValue;
    // Payments Requests Good Types
    private String goodTypes;
    // Payments Requests Payment Status
    private PaymentRequestStatus paymentStatus;


    // CONSTRUCTORS ------------------------------------------------------------


	/**
	 * Empty Constructor
	 **/
	public PaymentsRequestsDAO() {
        // Set cache object type
		this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
	}


	/**
	 * Type Constructor
	 **/
	public PaymentsRequestsDAO(SearchType type) {
        // Set DAO Search type
        this.setSearchType(type);
        // Set cache object type
		this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
	}
	
	
    /**
     * Payments Request Bean Field Constructor
     * @param id long Payments Requests Identifier
     */
    public PaymentsRequestsDAO(long id) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Payments Requests Identifier
        setId(id);
    }


    /**
     * Payments Request Bean Field Constructor
     * @param id long Payments Requests Identifier
     * @param idShop long Payments Requests Shop Identifier
     * @param idCashier long Payments Requests Cashier Identifier
     * @param idVolunteer long Payments Requests Volunteer Identifier
     * @param idPaymentCode long Payments Requests Payment Code Identifier
     * @param transactionValue float Payments Requests Transaction Value
     * @param paymentStatus PaymentRequestStatus Payments Requests Payment Status
     */
    public PaymentsRequestsDAO(long id, long idShop, long idCashier
                    , long idVolunteer, long idPaymentCode, float transactionValue
                    , PaymentRequestStatus paymentStatus) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Payments Requests Identifier
        setId(id);
        // Set Payments Requests Shop Identifier
        setIdShop(idShop);
        // Set Payments Requests Cashier Identifier
        setIdCashier(idCashier);
        // Set Payments Requests Volunteer Identifier
        setIdVolunteer(idVolunteer);
        // Set Payments Requests Payment Code Identifier
        setIdPaymentCode(idPaymentCode);
        // Set Payments Requests Transaction Value
        setTransactionValue(transactionValue);
        // Set Payments Requests Payment Status
        setPaymentStatus(paymentStatus);
    }


    /**
     * Payments Request Bean Field Constructor
     * @param id long Payments Requests Identifier
     * @param idShop long Payments Requests Shop Identifier
     * @param idCashier long Payments Requests Cashier Identifier
     * @param idVolunteer long Payments Requests Volunteer Identifier
     * @param idPaymentCode long Payments Requests Payment Code Identifier
     * @param transactionValue float Payments Requests Transaction Value
     * @param goodTypes String Payments Requests Good Types
     * @param paymentStatus PaymentRequestStatus Payments Requests Payment Status
     */
    public PaymentsRequestsDAO(long id, long idShop, long idCashier
                    , long idVolunteer, long idPaymentCode, float transactionValue
                    , String goodTypes, PaymentRequestStatus paymentStatus) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Payments Requests Identifier
        setId(id);
        // Set Payments Requests Shop Identifier
        setIdShop(idShop);
        // Set Payments Requests Cashier Identifier
        setIdCashier(idCashier);
        // Set Payments Requests Volunteer Identifier
        setIdVolunteer(idVolunteer);
        // Set Payments Requests Payment Code Identifier
        setIdPaymentCode(idPaymentCode);
        // Set Payments Requests Transaction Value
        setTransactionValue(transactionValue);
        // Set Payments Requests Good Types
        setGoodTypes(goodTypes);
        // Set Payments Requests Payment Status
        setPaymentStatus(paymentStatus);
    }


    

    
    // TYPE -------------------------------------------------------------------

    
    /**
     * Sets DAO search type
     * @param type
     */
    public void setSearchType(SearchType type) {
    	// Sets DAO type
    	super.setSearchType(type);
    }


	// GETTERS -----------------------------------------------------------------


    /**
     * Get Payments Requests Identifier
     * @return long Payments Requests Identifier
     */
    public long getId() {
        return this.id;
    }


    /**
     * Get Payments Requests Shop Identifier
     * @return long Payments Requests Shop Identifier
     */
    public long getIdShop() {
        return this.idShop;
    }


    /**
     * Get Payments Requests Cashier Identifier
     * @return long Payments Requests Cashier Identifier
     */
    public long getIdCashier() {
        return this.idCashier;
    }


    /**
     * Get Payments Requests Volunteer Identifier
     * @return long Payments Requests Volunteer Identifier
     */
    public long getIdVolunteer() {
        return this.idVolunteer;
    }


    /**
     * Get Payments Requests Payment Code Identifier
     * @return long Payments Requests Payment Code Identifier
     */
    public long getIdPaymentCode() {
        return this.idPaymentCode;
    }


    /**
     * Get Payments Requests Transaction Value
     * @return float Payments Requests Transaction Value
     */
    public float getTransactionValue() {
        return this.transactionValue;
    }


    /**
     * Get Payments Requests Good Types
     * @return String Payments Requests Good Types
     */
    public String getGoodTypes() {
        return this.goodTypes;
    }


    /**
     * Get Payments Requests Payment Status
     * @return PaymentRequestStatus Payments Requests Payment Status
     */
    public PaymentRequestStatus getPaymentStatus() {
        return this.paymentStatus;
    }



	// SETTERS -----------------------------------------------------------------


    /**
     * Set Payments Requests Identifier
     * @param id long Payments Requests Identifier
     */
    public void setId(long id) {
        this.id = id;
    }


    /**
     * Set Payments Requests Shop Identifier
     * @param idShop long Payments Requests Shop Identifier
     */
    public void setIdShop(long idShop) {
        this.idShop = idShop;
    }


    /**
     * Set Payments Requests Cashier Identifier
     * @param idCashier long Payments Requests Cashier Identifier
     */
    public void setIdCashier(long idCashier) {
        this.idCashier = idCashier;
    }


    /**
     * Set Payments Requests Volunteer Identifier
     * @param idVolunteer long Payments Requests Volunteer Identifier
     */
    public void setIdVolunteer(long idVolunteer) {
        this.idVolunteer = idVolunteer;
    }


    /**
     * Set Payments Requests Payment Code Identifier
     * @param idPaymentCode long Payments Requests Payment Code Identifier
     */
    public void setIdPaymentCode(long idPaymentCode) {
        this.idPaymentCode = idPaymentCode;
    }


    /**
     * Set Payments Requests Transaction Value
     * @param transactionValue float Payments Requests Transaction Value
     */
    public void setTransactionValue(float transactionValue) {
        this.transactionValue = transactionValue;
    }


    /**
     * Set Payments Requests Good Types
     * @param goodTypes String Payments Requests Good Types
     */
    public void setGoodTypes(String goodTypes) {
        this.goodTypes = goodTypes;
    }


    /**
     * Set Payments Requests Payment Status
     * @param paymentStatus PaymentRequestStatus Payments Requests Payment Status
     */
    public void setPaymentStatus(PaymentRequestStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }



    // MULTI-LANGUAGE ---------------------------------------------------------



	// DAO ID -----------------------------------------------------------------

    
    /**
     * Checks if has Id Field
     */
    public boolean hasIdField() {
    	return true;
    }

    
    /**
     * Sets Id
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }


    // CACHING ----------------------------------------------------------------
    
    
	/**
	 * Gets cachePrefix
	 * @return The cachePrefix of this object
	 */
	public String getCachePrefix() {
		return CACHE_PREFIX;
	}
	
	
	/**
	 * Gets the object cache keys
	 * @return cacheKeys
	 */
	public String[] getCacheKeys() {
		if (getParameters() != null) {
			return getParameters().getCacheKeys();
		}
		return null;
	}
	

    // DATABASE MANAGER SPECIFIC ----------------------------------------------

    
    /**
     * Gets table name
     */
    public String getTableName() {
    	return "PAYMENTS_REQUESTS";
    }

    
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
    public String getDBConnectionName() {
    	return "Merits_Merits";
    }

    
    /**
     * Gets Insert query SQL
     * @return Insert SQL
     */
    public String getInsertSQL() {
    	// SQL
    	return "INSERT INTO PAYMENTS_REQUESTS (`ID_SHOP`, `ID_CASHIER`, `ID_VOLUNTEER`, `ID_PAYMENT_CODE`, `TRANSACTION_VALUE`, `GOOD_TYPES`, `PAYMENT_STATUS`) values (?, ?, ?, ?, ?, ?, ?)";
    }

    
    /**
     * Gets Insert procedure
     */
    public String getInsertProcedureName() {
    	return "PAYMENTS_REQUESTS_PROC(?, ?, ?, ?, ?, ?, ?, ?)";
    }


	// RESULTSETS & STATEMENTS ------------------------------------------------
	    
    
    /**
     * Fills insert fields
     * @param statement
     */
    public void fillStatementFieldsForInsert(CallableStatement statement) throws Exception {
        // Set Payments Requests Shop Identifier
        statement.setLong(1, idShop);
        // Set Payments Requests Cashier Identifier
        statement.setLong(2, idCashier);
        // Set Payments Requests Volunteer Identifier
        statement.setLong(3, idVolunteer);
        // Set Payments Requests Payment Code Identifier
        statement.setLong(4, idPaymentCode);
        // Set Payments Requests Transaction Value
        statement.setFloat(5, transactionValue);
        // Check If Payments Requests Good Types Is Null
        if (goodTypes == null) {
            statement.setNull(6, java.sql.Types.VARCHAR);
        } else {
            // Set Payments Requests Good Types
            statement.setString(6, StringUtilities.capString(goodTypes,250));
        }
        // Set Payments Requests Payment Status
        statement.setInt(7, paymentStatus.getValue());
    }


    /**
     * Sets DAO values from a resultset 
     * @param resultset
     */
    public void fillValuesFromResultSet(ResultSet resultset) throws Exception {
        // Set Payments Requests Identifier
        this.setId(resultset.getLong("ID"));
        // Set Payments Requests Shop Identifier
        this.setIdShop(resultset.getLong("ID_SHOP"));
        // Set Payments Requests Cashier Identifier
        this.setIdCashier(resultset.getLong("ID_CASHIER"));
        // Set Payments Requests Volunteer Identifier
        this.setIdVolunteer(resultset.getLong("ID_VOLUNTEER"));
        // Set Payments Requests Payment Code Identifier
        this.setIdPaymentCode(resultset.getLong("ID_PAYMENT_CODE"));
        // Set Payments Requests Transaction Value
        this.setTransactionValue(resultset.getFloat("TRANSACTION_VALUE"));
        // Set Payments Requests Good Types
        this.setGoodTypes(resultset.getString("GOOD_TYPES"));
        // Check if was null
        if (resultset.wasNull()) {
            this.setGoodTypes(null);
        }
        // Set Payments Requests Payment Status
        this.setPaymentStatus(PaymentRequestStatus.getByValue(resultset.getInt("PAYMENT_STATUS")));
    }

    
    // ------------------------------------------------------------------------
    // PARAMETERS CLASSES -----------------------------------------------------
    // ------------------------------------------------------------------------


}
