package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import java.sql.CallableStatement;
import java.sql.Timestamp;

import com.weezzi.core.data.*;
import com.weezzi.core.dbmanager.dao.UpdaterDAO;
import com.weezzi.utils.StringUtilities;
import com.merits.modules.base.uobjects.enums.PaymentRequestStatus;


/**
 * <b>Title: </b>Payments Request Updater Object<br/>
 * <b>Description: </b>Payments Request Updater Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
 @SuppressWarnings("unused")
public class PaymentsRequestsUpdater implements UpdaterDAO {


    // PROPERTIES --------------------------------------------------------------

    private long id;
    private long idShop;
    private long idCashier;
    private long idVolunteer;
    private long idPaymentCode;
    private float transactionValue;
    private String goodTypes;
    private PaymentRequestStatus paymentStatus;


    // CONSTRUCTORS ------------------------------------------------------------


	/**
	 * Empty Constructor
	 **/
	public PaymentsRequestsUpdater(long id, long idShop, long idCashier, long idVolunteer, long idPaymentCode, float transactionValue, String goodTypes, PaymentRequestStatus paymentStatus) {
        this.id = id;
        this.idShop = idShop;
        this.idCashier = idCashier;
        this.idVolunteer = idVolunteer;
        this.idPaymentCode = idPaymentCode;
        this.transactionValue = transactionValue;
        this.goodTypes = goodTypes;
        this.paymentStatus = paymentStatus;
	}


	// PUBLIC -----------------------------------------------------------------

	
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
	public String getDBConnectionName() {
		return "Merits_Merits";
	}


	/**
	 * Gets update SQL
	 * @return query
	 */
	public String getQuerySQL() {
		return "UPDATE PAYMENTS_REQUESTS " +
               " SET ID_SHOP = ? , ID_CASHIER = ? , ID_VOLUNTEER = ? , ID_PAYMENT_CODE = ? , TRANSACTION_VALUE = ? , GOOD_TYPES = ? , PAYMENT_STATUS = ?  " +
               " WHERE  ID = ?";
	}
	
	
	/**
	 * Updates Query Fields
	 * @param statment
	 * @throws Exception
	 */
	public void updateFields(CallableStatement statement) throws Exception {
        // Set Fields
        statement.setLong(1, idShop);
        statement.setLong(2, idCashier);
        statement.setLong(3, idVolunteer);
        statement.setLong(4, idPaymentCode);
        statement.setFloat(5, transactionValue);
        // Check If Null
        if (goodTypes == null) {
            statement.setNull(6, java.sql.Types.VARCHAR);
        } else {
            statement.setString(6, StringUtilities.capString(goodTypes, 250));
        }
        // Check If Null
        if (paymentStatus == null) {
            statement.setNull(7, java.sql.Types.VARCHAR);
        } else {
            statement.setInt(7, paymentStatus.getValue());
        }
        statement.setLong(8, id);
	}


	/**
	 * Gets extended update SQL
	 * @return query
	 */
	public String getExtendedQuerySQL() {
		return null;
	}
	
	
	/**
	 * Updates Extended Query Fields
	 * @param statment
	 * @throws Exception
	 */
	public void updateExtendedQueryFields(CallableStatement statement) throws Exception {
	}
	
	
}
