package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import java.sql.CallableStatement;
import java.sql.Timestamp;

import com.weezzi.core.data.*;
import com.weezzi.core.dbmanager.dao.UpdaterDAO;
import com.weezzi.utils.StringUtilities;


/**
 * <b>Title: </b>Project Updater Object<br/>
 * <b>Description: </b>Project Updater Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
 @SuppressWarnings("unused")
public class ProjectsUpdaterByAll implements UpdaterDAO {


    // PROPERTIES --------------------------------------------------------------

    private long id;
    private String name;
    private String headline;
    private String description;
    private boolean hasDonations;
    private boolean hasVolunteers;
    private long volunteersWanted;
    private long donationsWanted;
    private Image photo;
    private ImageList imagesList;
    private UpdateInfo _updateInfo;
    private String langCode;


    // CONSTRUCTORS ------------------------------------------------------------


	/**
	 * Empty Constructor
	 **/
	public ProjectsUpdaterByAll(long id, String name, String headline, String description, boolean hasDonations, boolean hasVolunteers, long volunteersWanted, long donationsWanted, Image photo, ImageList imagesList, String langCode, UpdateInfo updateInfo) {
        this.id = id;
        this.name = name;
        this.headline = headline;
        this.description = description;
        this.hasDonations = hasDonations;
        this.hasVolunteers = hasVolunteers;
        this.volunteersWanted = volunteersWanted;
        this.donationsWanted = donationsWanted;
        this.photo = photo;
        this.imagesList = imagesList;
        this._updateInfo = updateInfo;
        this.langCode = langCode;
	}


	// PUBLIC -----------------------------------------------------------------

	
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
	public String getDBConnectionName() {
		return "Merits_Merits";
	}


	/**
	 * Gets update SQL
	 * @return query
	 */
	public String getQuerySQL() {
		return "UPDATE PROJECTS, `weezziserver`.`MULTILANG_TRANSLATIONS` " +
               " SET `weezziserver`.MULTILANG_TRANSLATIONS.SMALL_TEXT1 = ? , `weezziserver`.MULTILANG_TRANSLATIONS.MEDIUM_TEXT1 = ? , HAS_DONATIONS = ? , `weezziserver`.MULTILANG_TRANSLATIONS.LARGE_TEXT1 = ? , HAS_VOLUNTEERS = ? , VOLUNTEERS_WANTED = ? , DONATIONS_WANTED = ? , PHOTO = ? , IMAGES_LIST = ? , EDIT_INFO_UPDATE_DATE  = ? , EDIT_INFO_UPDATE_USER  = ?  " +
               " WHERE PROJECTS.MLK_ID = `weezziserver`.MULTILANG_TRANSLATIONS.ID_MLK AND `weezziserver`.MULTILANG_TRANSLATIONS.LANG_CODE = ? AND PROJECTS.ID = ?";
	}
	
	
	/**
	 * Updates Query Fields
	 * @param statment
	 * @throws Exception
	 */
	public void updateFields(CallableStatement statement) throws Exception {
        // Set Fields
        statement.setString(1, name);
        statement.setString(2, headline);
        statement.setBoolean(3, hasDonations);
        statement.setString(4, description);
        statement.setBoolean(5, hasVolunteers);
        statement.setLong(6, volunteersWanted);
        statement.setLong(7, donationsWanted);
        // Check If Null
        if (photo == null) {
            statement.setNull(8, java.sql.Types.VARCHAR);
        } else {
            statement.setString(8, photo.serialize());
        }
        // Check If Null
        if (imagesList == null) {
            statement.setNull(9, java.sql.Types.VARCHAR);
        } else {
            statement.setString(9, imagesList.serialize());
        }
        // Check if edit info update date is Null
        if (_updateInfo.getUpdateDate() == null) {
            statement.setNull(10, java.sql.Types.TIMESTAMP);
        } else {
            // Set update date
            statement.setTimestamp(10,  _updateInfo.getUpdateDate());
        } 
        // Check if edit info update user is Null
        if (_updateInfo.getUpdateUserId() == null) {
            statement.setNull(11, java.sql.Types.NUMERIC);
        } else {
            // Set update user
            statement.setLong(11, _updateInfo.getUpdateUserId());
        } 
        // Set multilang language code
        statement.setString(12, langCode);
        statement.setLong(13, id);
	}


	/**
	 * Gets extended update SQL
	 * @return query
	 */
	public String getExtendedQuerySQL() {
		return " UPDATE PROJECTS SET MLK_LANGS = (" + 
                "SELECT group_concat(lang_code) FROM (SELECT MLK_ID FROM PROJECTS WHERE ID=?) AS TEMP, `weezziserver`.multilang_translations " + 
                "WHERE `weezziserver`.multilang_translations.id_mlk= TEMP.MLK_ID " + 
                    "AND length(`weezziserver`.multilang_translations.SMALL_TEXT1) > 0 " + 
                    "AND length(`weezziserver`.multilang_translations.MEDIUM_TEXT1) > 0 " + 
                    "AND length(`weezziserver`.multilang_translations.LARGE_TEXT1) > 0 " + 
                ") WHERE ID = ?";
	}
	
	
	/**
	 * Updates Extended Query Fields
	 * @param statment
	 * @throws Exception
	 */
	public void updateExtendedQueryFields(CallableStatement statement) throws Exception {
        statement.setLong(1, id);
        statement.setLong(2, id);
	}
	
	
}
