package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import java.sql.CallableStatement;
import java.sql.Timestamp;

import com.weezzi.core.data.*;
import com.weezzi.core.dbmanager.dao.UpdaterDAO;
import com.weezzi.utils.StringUtilities;
import com.weezzi.utils.SecurityUtilities;


/**
 * <b>Title: </b>Shop Updater Object<br/>
 * <b>Description: </b>Shop Updater Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
 @SuppressWarnings("unused")
public class ShopsUpdaterByPassword implements UpdaterDAO {


    // PROPERTIES --------------------------------------------------------------

    private long id;
    private String ownerPassword;
    private UpdateInfo _updateInfo;


    // CONSTRUCTORS ------------------------------------------------------------


	/**
	 * Empty Constructor
	 **/
	public ShopsUpdaterByPassword(long id, String ownerPassword, UpdateInfo updateInfo) {
        this.id = id;
        this.ownerPassword = ownerPassword;
        this._updateInfo = updateInfo;
	}


	// PUBLIC -----------------------------------------------------------------

	
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
	public String getDBConnectionName() {
		return "Merits_Merits";
	}


	/**
	 * Gets update SQL
	 * @return query
	 */
	public String getQuerySQL() {
		return "UPDATE SHOPS " +
               " SET OWNER_PASSWORD = ? , EDIT_INFO_UPDATE_DATE  = ? , EDIT_INFO_UPDATE_USER  = ?  " +
               " WHERE  ID = ?";
	}
	
	
	/**
	 * Updates Query Fields
	 * @param statment
	 * @throws Exception
	 */
	public void updateFields(CallableStatement statement) throws Exception {
        // Set Fields
        statement.setString(1, SecurityUtilities.encryptSalted(ownerPassword, "SHOPS", "OWNER_PASSWORD", id));
        // Check if edit info update date is Null
        if (_updateInfo.getUpdateDate() == null) {
            statement.setNull(2, java.sql.Types.TIMESTAMP);
        } else {
            // Set update date
            statement.setTimestamp(2,  _updateInfo.getUpdateDate());
        } 
        // Check if edit info update user is Null
        if (_updateInfo.getUpdateUserId() == null) {
            statement.setNull(3, java.sql.Types.NUMERIC);
        } else {
            // Set update user
            statement.setLong(3, _updateInfo.getUpdateUserId());
        } 
        statement.setLong(4, id);
	}


	/**
	 * Gets extended update SQL
	 * @return query
	 */
	public String getExtendedQuerySQL() {
		return null;
	}
	
	
	/**
	 * Updates Extended Query Fields
	 * @param statment
	 * @throws Exception
	 */
	public void updateExtendedQueryFields(CallableStatement statement) throws Exception {
	}
	
	
}
