package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import com.weezzi.core.data.*;
import com.weezzi.core.dbmanager.dao.SingleRecordDAO;
import com.weezzi.utils.StringUtilities;
import com.weezzi.utils.extras.cache.WeezziCacheObjectType;
import com.weezzi.utils.extras.console.Console;


import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;



/**
 * <b>Title: </b>Shop Transactions Good Data Access Object<br/>
 * <b>Description: </b>Shop Transactions Good DAO Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
public class ShopTransactionsGoodsDAO extends SingleRecordDAO {


	// CONSTANTS --------------------------------------------------------------

	
	public static final String CACHE_PREFIX = "D11#";
	private static final long serialVersionUID = 1l;


    // MULTI-LANGUAGE ---------------------------------------------------------


    /**
     *  Multi-Language
     */
    public enum MultiLanguageFields {
        ;

        private String column;

        MultiLanguageFields(String column) {
        	this.column = column;
        }

        public String getColumnName() {
        	return column;
        }
	}


    // DATA TYPE ENUMERATION --------------------------------------------------


    /**
     *  DAO Search Type
     */
    public enum SearchType {

    	// Single Record Queries

		;
    	
        private String cachePrefix;
        
        SearchType(String cachePrefix) {
        	this.cachePrefix = cachePrefix;
        }

        /**
         * Gets cache prefix
         **/
        public String toString() {
        	return cachePrefix;
        }
    }


    // PROPERTIES --------------------------------------------------------------

    // Shop Transactions Goods Identifier
    private long id;
    // Shop Transactions Goods Shop Identifier
    private long idShop;
    // Shop Transactions Goods Cashier Identifier
    private long idCashier;
    // Shop Transactions Goods Good Type Identifier
    private long idGoodType;
    // Shop Transactions Goods Shop Transaction Identifier
    private long idShopTransaction;
    // Shop Transactions Goods Transaction Date
    private Timestamp transactionDate;


    // CONSTRUCTORS ------------------------------------------------------------


	/**
	 * Empty Constructor
	 **/
	public ShopTransactionsGoodsDAO() {
        // Set cache object type
		this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
	}


	/**
	 * Type Constructor
	 **/
	public ShopTransactionsGoodsDAO(SearchType type) {
        // Set DAO Search type
        this.setSearchType(type);
        // Set cache object type
		this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
	}
	
	
    /**
     * Shop Transactions Good Bean Field Constructor
     * @param id long Shop Transactions Goods Identifier
     */
    public ShopTransactionsGoodsDAO(long id) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Shop Transactions Goods Identifier
        setId(id);
    }


    /**
     * Shop Transactions Good Bean Field Constructor
     * @param id long Shop Transactions Goods Identifier
     * @param idShop long Shop Transactions Goods Shop Identifier
     * @param idCashier long Shop Transactions Goods Cashier Identifier
     * @param idGoodType long Shop Transactions Goods Good Type Identifier
     * @param idShopTransaction long Shop Transactions Goods Shop Transaction Identifier
     * @param transactionDate Timestamp Shop Transactions Goods Transaction Date
     */
    public ShopTransactionsGoodsDAO(long id, long idShop, long idCashier
                    , long idGoodType, long idShopTransaction, Timestamp transactionDate) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Shop Transactions Goods Identifier
        setId(id);
        // Set Shop Transactions Goods Shop Identifier
        setIdShop(idShop);
        // Set Shop Transactions Goods Cashier Identifier
        setIdCashier(idCashier);
        // Set Shop Transactions Goods Good Type Identifier
        setIdGoodType(idGoodType);
        // Set Shop Transactions Goods Shop Transaction Identifier
        setIdShopTransaction(idShopTransaction);
        // Set Shop Transactions Goods Transaction Date
        setTransactionDate(transactionDate);
    }


    

    
    // TYPE -------------------------------------------------------------------

    
    /**
     * Sets DAO search type
     * @param type
     */
    public void setSearchType(SearchType type) {
    	// Sets DAO type
    	super.setSearchType(type);
    }


	// GETTERS -----------------------------------------------------------------


    /**
     * Get Shop Transactions Goods Identifier
     * @return long Shop Transactions Goods Identifier
     */
    public long getId() {
        return this.id;
    }


    /**
     * Get Shop Transactions Goods Shop Identifier
     * @return long Shop Transactions Goods Shop Identifier
     */
    public long getIdShop() {
        return this.idShop;
    }


    /**
     * Get Shop Transactions Goods Cashier Identifier
     * @return long Shop Transactions Goods Cashier Identifier
     */
    public long getIdCashier() {
        return this.idCashier;
    }


    /**
     * Get Shop Transactions Goods Good Type Identifier
     * @return long Shop Transactions Goods Good Type Identifier
     */
    public long getIdGoodType() {
        return this.idGoodType;
    }


    /**
     * Get Shop Transactions Goods Shop Transaction Identifier
     * @return long Shop Transactions Goods Shop Transaction Identifier
     */
    public long getIdShopTransaction() {
        return this.idShopTransaction;
    }


    /**
     * Get Shop Transactions Goods Transaction Date
     * @return Timestamp Shop Transactions Goods Transaction Date
     */
    public Timestamp getTransactionDate() {
        return this.transactionDate;
    }



	// SETTERS -----------------------------------------------------------------


    /**
     * Set Shop Transactions Goods Identifier
     * @param id long Shop Transactions Goods Identifier
     */
    public void setId(long id) {
        this.id = id;
    }


    /**
     * Set Shop Transactions Goods Shop Identifier
     * @param idShop long Shop Transactions Goods Shop Identifier
     */
    public void setIdShop(long idShop) {
        this.idShop = idShop;
    }


    /**
     * Set Shop Transactions Goods Cashier Identifier
     * @param idCashier long Shop Transactions Goods Cashier Identifier
     */
    public void setIdCashier(long idCashier) {
        this.idCashier = idCashier;
    }


    /**
     * Set Shop Transactions Goods Good Type Identifier
     * @param idGoodType long Shop Transactions Goods Good Type Identifier
     */
    public void setIdGoodType(long idGoodType) {
        this.idGoodType = idGoodType;
    }


    /**
     * Set Shop Transactions Goods Shop Transaction Identifier
     * @param idShopTransaction long Shop Transactions Goods Shop Transaction Identifier
     */
    public void setIdShopTransaction(long idShopTransaction) {
        this.idShopTransaction = idShopTransaction;
    }


    /**
     * Set Shop Transactions Goods Transaction Date
     * @param transactionDate Timestamp Shop Transactions Goods Transaction Date
     */
    public void setTransactionDate(Timestamp transactionDate) {
        this.transactionDate = transactionDate;
    }



    // MULTI-LANGUAGE ---------------------------------------------------------



	// DAO ID -----------------------------------------------------------------

    
    /**
     * Checks if has Id Field
     */
    public boolean hasIdField() {
    	return true;
    }

    
    /**
     * Sets Id
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }


    // CACHING ----------------------------------------------------------------
    
    
	/**
	 * Gets cachePrefix
	 * @return The cachePrefix of this object
	 */
	public String getCachePrefix() {
		return CACHE_PREFIX;
	}
	
	
	/**
	 * Gets the object cache keys
	 * @return cacheKeys
	 */
	public String[] getCacheKeys() {
		if (getParameters() != null) {
			return getParameters().getCacheKeys();
		}
		return null;
	}
	

    // DATABASE MANAGER SPECIFIC ----------------------------------------------

    
    /**
     * Gets table name
     */
    public String getTableName() {
    	return "SHOP_TRANSACTIONS_GOODS";
    }

    
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
    public String getDBConnectionName() {
    	return "Merits_Merits";
    }

    
    /**
     * Gets Insert query SQL
     * @return Insert SQL
     */
    public String getInsertSQL() {
    	// SQL
    	return "INSERT INTO SHOP_TRANSACTIONS_GOODS (`ID_SHOP`, `ID_CASHIER`, `ID_GOOD_TYPE`, `ID_SHOP_TRANSACTION`, `TRANSACTION_DATE`) values (?, ?, ?, ?, ?)";
    }

    
    /**
     * Gets Insert procedure
     */
    public String getInsertProcedureName() {
    	return "SHOP_TRANSACTIONS_GOODS_PROC(?, ?, ?, ?, ?, ?)";
    }


	// RESULTSETS & STATEMENTS ------------------------------------------------
	    
    
    /**
     * Fills insert fields
     * @param statement
     */
    public void fillStatementFieldsForInsert(CallableStatement statement) throws Exception {
        // Set Shop Transactions Goods Shop Identifier
        statement.setLong(1, idShop);
        // Set Shop Transactions Goods Cashier Identifier
        statement.setLong(2, idCashier);
        // Set Shop Transactions Goods Good Type Identifier
        statement.setLong(3, idGoodType);
        // Set Shop Transactions Goods Shop Transaction Identifier
        statement.setLong(4, idShopTransaction);
        // Set Shop Transactions Goods Transaction Date
        statement.setTimestamp(5, transactionDate);
    }


    /**
     * Sets DAO values from a resultset 
     * @param resultset
     */
    public void fillValuesFromResultSet(ResultSet resultset) throws Exception {
        // Set Shop Transactions Goods Identifier
        this.setId(resultset.getLong("ID"));
        // Set Shop Transactions Goods Shop Identifier
        this.setIdShop(resultset.getLong("ID_SHOP"));
        // Set Shop Transactions Goods Cashier Identifier
        this.setIdCashier(resultset.getLong("ID_CASHIER"));
        // Set Shop Transactions Goods Good Type Identifier
        this.setIdGoodType(resultset.getLong("ID_GOOD_TYPE"));
        // Set Shop Transactions Goods Shop Transaction Identifier
        this.setIdShopTransaction(resultset.getLong("ID_SHOP_TRANSACTION"));
        // Set Shop Transactions Goods Transaction Date
        this.setTransactionDate(resultset.getTimestamp("TRANSACTION_DATE", SingleRecordDAO.TIMEZONE));
    }

    
    // ------------------------------------------------------------------------
    // PARAMETERS CLASSES -----------------------------------------------------
    // ------------------------------------------------------------------------


}
