package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import java.sql.CallableStatement;
import java.sql.Timestamp;

import com.weezzi.core.data.*;
import com.weezzi.core.dbmanager.dao.UpdaterDAO;
import com.weezzi.utils.StringUtilities;


/**
 * <b>Title: </b>Shop Transactions Good Updater Object<br/>
 * <b>Description: </b>Shop Transactions Good Updater Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
 @SuppressWarnings("unused")
public class ShopTransactionsGoodsUpdater implements UpdaterDAO {


    // PROPERTIES --------------------------------------------------------------

    private long id;
    private long idShop;
    private long idCashier;
    private long idGoodType;
    private long idShopTransaction;
    private Timestamp transactionDate;


    // CONSTRUCTORS ------------------------------------------------------------


	/**
	 * Empty Constructor
	 **/
	public ShopTransactionsGoodsUpdater(long id, long idShop, long idCashier, long idGoodType, long idShopTransaction, Timestamp transactionDate) {
        this.id = id;
        this.idShop = idShop;
        this.idCashier = idCashier;
        this.idGoodType = idGoodType;
        this.idShopTransaction = idShopTransaction;
        this.transactionDate = transactionDate;
	}


	// PUBLIC -----------------------------------------------------------------

	
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
	public String getDBConnectionName() {
		return "Merits_Merits";
	}


	/**
	 * Gets update SQL
	 * @return query
	 */
	public String getQuerySQL() {
		return "UPDATE SHOP_TRANSACTIONS_GOODS " +
               " SET ID_SHOP = ? , ID_CASHIER = ? , ID_GOOD_TYPE = ? , ID_SHOP_TRANSACTION = ? , TRANSACTION_DATE = ?  " +
               " WHERE  ID = ?";
	}
	
	
	/**
	 * Updates Query Fields
	 * @param statment
	 * @throws Exception
	 */
	public void updateFields(CallableStatement statement) throws Exception {
        // Set Fields
        statement.setLong(1, idShop);
        statement.setLong(2, idCashier);
        statement.setLong(3, idGoodType);
        statement.setLong(4, idShopTransaction);
        statement.setTimestamp(5, transactionDate);
        statement.setLong(6, id);
	}


	/**
	 * Gets extended update SQL
	 * @return query
	 */
	public String getExtendedQuerySQL() {
		return null;
	}
	
	
	/**
	 * Updates Extended Query Fields
	 * @param statment
	 * @throws Exception
	 */
	public void updateExtendedQueryFields(CallableStatement statement) throws Exception {
	}
	
	
}
