package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import java.sql.CallableStatement;
import java.sql.Timestamp;

import com.weezzi.core.data.*;
import com.weezzi.core.dbmanager.dao.UpdaterDAO;
import com.weezzi.utils.StringUtilities;


/**
 * <b>Title: </b>Team Updater Object<br/>
 * <b>Description: </b>Team Updater Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
 @SuppressWarnings("unused")
public class TeamUpdaterByAll implements UpdaterDAO {


    // PROPERTIES --------------------------------------------------------------

    private long id;
    private String name;
    private String position;
    private String description;
    private Image photo;
    private String instagramUrl;
    private String twitterUrl;
    private String facebookUrl;
    private UpdateInfo _updateInfo;
    private String langCode;


    // CONSTRUCTORS ------------------------------------------------------------


	/**
	 * Empty Constructor
	 **/
	public TeamUpdaterByAll(long id, String name, String position, String description, Image photo, String instagramUrl, String twitterUrl, String facebookUrl, String langCode, UpdateInfo updateInfo) {
        this.id = id;
        this.name = name;
        this.position = position;
        this.description = description;
        this.photo = photo;
        this.instagramUrl = instagramUrl;
        this.twitterUrl = twitterUrl;
        this.facebookUrl = facebookUrl;
        this._updateInfo = updateInfo;
        this.langCode = langCode;
	}


	// PUBLIC -----------------------------------------------------------------

	
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
	public String getDBConnectionName() {
		return "Merits_Merits";
	}


	/**
	 * Gets update SQL
	 * @return query
	 */
	public String getQuerySQL() {
		return "UPDATE TEAM, `weezziserver`.`MULTILANG_TRANSLATIONS` " +
               " SET FACEBOOK_URL = ? , TWITTER_URL = ? , INSTAGRAM_URL = ? , PHOTO = ? , `weezziserver`.MULTILANG_TRANSLATIONS.MEDIUM_TEXT1 = ? , `weezziserver`.MULTILANG_TRANSLATIONS.SMALL_TEXT1 = ? , NAME = ? , EDIT_INFO_UPDATE_DATE  = ? , EDIT_INFO_UPDATE_USER  = ?  " +
               " WHERE TEAM.MLK_ID = `weezziserver`.MULTILANG_TRANSLATIONS.ID_MLK AND `weezziserver`.MULTILANG_TRANSLATIONS.LANG_CODE = ? AND TEAM.ID = ?";
	}
	
	
	/**
	 * Updates Query Fields
	 * @param statment
	 * @throws Exception
	 */
	public void updateFields(CallableStatement statement) throws Exception {
        // Set Fields
        // Check If Null
        if (facebookUrl == null) {
            statement.setNull(1, java.sql.Types.VARCHAR);
        } else {
            statement.setString(1, StringUtilities.capString(facebookUrl, 150));
        }
        // Check If Null
        if (twitterUrl == null) {
            statement.setNull(2, java.sql.Types.VARCHAR);
        } else {
            statement.setString(2, StringUtilities.capString(twitterUrl, 150));
        }
        // Check If Null
        if (instagramUrl == null) {
            statement.setNull(3, java.sql.Types.VARCHAR);
        } else {
            statement.setString(3, StringUtilities.capString(instagramUrl, 150));
        }
        // Check If Null
        if (photo == null) {
            statement.setNull(4, java.sql.Types.VARCHAR);
        } else {
            statement.setString(4, photo.serialize());
        }
        statement.setString(5, description);
        statement.setString(6, position);
        statement.setString(7, StringUtilities.capString(name, 100));
        // Check if edit info update date is Null
        if (_updateInfo.getUpdateDate() == null) {
            statement.setNull(8, java.sql.Types.TIMESTAMP);
        } else {
            // Set update date
            statement.setTimestamp(8,  _updateInfo.getUpdateDate());
        } 
        // Check if edit info update user is Null
        if (_updateInfo.getUpdateUserId() == null) {
            statement.setNull(9, java.sql.Types.NUMERIC);
        } else {
            // Set update user
            statement.setLong(9, _updateInfo.getUpdateUserId());
        } 
        // Set multilang language code
        statement.setString(10, langCode);
        statement.setLong(11, id);
	}


	/**
	 * Gets extended update SQL
	 * @return query
	 */
	public String getExtendedQuerySQL() {
		return " UPDATE TEAM SET MLK_LANGS = (" + 
                "SELECT group_concat(lang_code) FROM (SELECT MLK_ID FROM TEAM WHERE ID=?) AS TEMP, `weezziserver`.multilang_translations " + 
                "WHERE `weezziserver`.multilang_translations.id_mlk= TEMP.MLK_ID " + 
                    "AND length(`weezziserver`.multilang_translations.SMALL_TEXT1) > 0 " + 
                    "AND length(`weezziserver`.multilang_translations.MEDIUM_TEXT1) > 0 " + 
                ") WHERE ID = ?";
	}
	
	
	/**
	 * Updates Extended Query Fields
	 * @param statment
	 * @throws Exception
	 */
	public void updateExtendedQueryFields(CallableStatement statement) throws Exception {
        statement.setLong(1, id);
        statement.setLong(2, id);
	}
	
	
}
