package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import com.weezzi.core.data.*;
import com.weezzi.core.dbmanager.dao.SingleRecordDAO;
import com.weezzi.utils.StringUtilities;
import com.weezzi.utils.extras.cache.WeezziCacheObjectType;
import com.weezzi.utils.extras.console.Console;


import java.sql.CallableStatement;
import java.sql.ResultSet;



/**
 * <b>Title: </b>Team Data Access Object<br/>
 * <b>Description: </b>Team DAO Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
public class TeamDAO extends SingleRecordDAO {


	// CONSTANTS --------------------------------------------------------------

	
	public static final String CACHE_PREFIX = "D14#";
	private static final long serialVersionUID = 1l;


    // MULTI-LANGUAGE ---------------------------------------------------------


    /**
     *  Multi-Language
     */
    public enum MultiLanguageFields {
        Position("SMALL_TEXT1"),
        Description("MEDIUM_TEXT1"),
        ;

        private String column;

        MultiLanguageFields(String column) {
        	this.column = column;
        }

        public String getColumnName() {
        	return column;
        }
	}


    // DATA TYPE ENUMERATION --------------------------------------------------


    /**
     *  DAO Search Type
     */
    public enum SearchType {

    	// Single Record Queries

		;
    	
        private String cachePrefix;
        
        SearchType(String cachePrefix) {
        	this.cachePrefix = cachePrefix;
        }

        /**
         * Gets cache prefix
         **/
        public String toString() {
        	return cachePrefix;
        }
    }


    // PROPERTIES --------------------------------------------------------------

    // Team Identifier
    private long id;
    // Team Name
    private String name;
    // Team Position
    private String position;
    // Team Description
    private String description;
    // Team Photo
    private Image photo;
    // Team Instagram Url
    private String instagramUrl;
    // Team Twitter Url
    private String twitterUrl;
    // Team Facebook Url
    private String facebookUrl;
    // Team Edit Info
    private EditInfo editInfo;
    // Team Publish Info
    private PublishInfo publishInfo;
    // Team Order Number
    private long orderNumber;
    // Multilanguage identifier
    private long multilangKeyId;
    // Multilanguage Translated Languages
    private String multilangKeyTranslations;


    // CONSTRUCTORS ------------------------------------------------------------


	/**
	 * Empty Constructor
	 **/
	public TeamDAO() {
        // Set cache object type
		this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
	}


	/**
	 * Type Constructor
	 **/
	public TeamDAO(SearchType type) {
        // Set DAO Search type
        this.setSearchType(type);
        // Set cache object type
		this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
	}
	
	
    /**
     * Team Bean Field Constructor
     * @param id long Team Identifier
     */
    public TeamDAO(long id) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Team Identifier
        setId(id);
    }


    /**
     * Team Bean Field Constructor
     * @param id long Team Identifier
     * @param name String Team Name
     * @param position String Team Position
     * @param description String Team Description
     * @param editInfo EditInfo Team Edit Info
     * @param publishInfo PublishInfo Team Publish Info
     */
    public TeamDAO(long id, String name, String position
                    , String description, EditInfo editInfo, PublishInfo publishInfo) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Team Identifier
        setId(id);
        // Set Team Name
        setName(name);
        // Set Team Position
        setPosition(position);
        // Set Team Description
        setDescription(description);
        // Set Team Edit Info
        setEditInfo(editInfo);
        // Set Team Publish Info
        setPublishInfo(publishInfo);
    }


    /**
     * Team Bean Field Constructor
     * @param id long Team Identifier
     * @param name String Team Name
     * @param position String Team Position
     * @param description String Team Description
     * @param photo Image Team Photo
     * @param instagramUrl String Team Instagram Url
     * @param twitterUrl String Team Twitter Url
     * @param facebookUrl String Team Facebook Url
     * @param editInfo EditInfo Team Edit Info
     * @param publishInfo PublishInfo Team Publish Info
     */
    public TeamDAO(long id, String name, String position
                    , String description, Image photo, String instagramUrl
                    , String twitterUrl, String facebookUrl, EditInfo editInfo
                    , PublishInfo publishInfo) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Team Identifier
        setId(id);
        // Set Team Name
        setName(name);
        // Set Team Position
        setPosition(position);
        // Set Team Description
        setDescription(description);
        // Set Team Photo
        setPhoto(photo);
        // Set Team Instagram Url
        setInstagramUrl(instagramUrl);
        // Set Team Twitter Url
        setTwitterUrl(twitterUrl);
        // Set Team Facebook Url
        setFacebookUrl(facebookUrl);
        // Set Team Edit Info
        setEditInfo(editInfo);
        // Set Team Publish Info
        setPublishInfo(publishInfo);
    }


    

    
    // TYPE -------------------------------------------------------------------

    
    /**
     * Sets DAO search type
     * @param type
     */
    public void setSearchType(SearchType type) {
    	// Sets DAO type
    	super.setSearchType(type);
    }


	// GETTERS -----------------------------------------------------------------


    /**
     * Get Team Identifier
     * @return long Team Identifier
     */
    public long getId() {
        return this.id;
    }


    /**
     * Get Team Name
     * @return String Team Name
     */
    public String getName() {
        return this.name;
    }


    /**
     * Get Team Position
     * @return String Team Position
     */
    public String getPosition() {
        return this.position;
    }


    /**
     * Get Team Description
     * @return String Team Description
     */
    public String getDescription() {
        return this.description;
    }


    /**
     * Get Team Photo
     * @return Image Team Photo
     */
    public Image getPhoto() {
        return this.photo;
    }


    /**
     * Get Team Instagram Url
     * @return String Team Instagram Url
     */
    public String getInstagramUrl() {
        return this.instagramUrl;
    }


    /**
     * Get Team Twitter Url
     * @return String Team Twitter Url
     */
    public String getTwitterUrl() {
        return this.twitterUrl;
    }


    /**
     * Get Team Facebook Url
     * @return String Team Facebook Url
     */
    public String getFacebookUrl() {
        return this.facebookUrl;
    }


    /**
     * Get Team Edit Info
     * @return EditInfo Team Edit Info
     */
    public EditInfo getEditInfo() {
        return this.editInfo;
    }


    /**
     * Get Team Publish Info
     * @return PublishInfo Team Publish Info
     */
    public PublishInfo getPublishInfo() {
        return this.publishInfo;
    }


    /**
     * Get Team Order Number
     * @return long Team Order Number
     */
    public long getOrderNumber() {
        return this.orderNumber;
    }


    /**
     * Get Multi-Language Identifier
     * @return long Multi-Language Identifier
     */
    public long getMultiLangKeyId() {
        return this.multilangKeyId;
    }


    /**
     * Get Multi-Language Translated Languages
     * @return long Multi-Language Translated Languages
     */
    public String getMultiLangKeyTranslations() {
        return this.multilangKeyTranslations;
    }



	// SETTERS -----------------------------------------------------------------


    /**
     * Set Team Identifier
     * @param id long Team Identifier
     */
    public void setId(long id) {
        this.id = id;
    }


    /**
     * Set Team Name
     * @param name String Team Name
     */
    public void setName(String name) {
        this.name = name;
    }


    /**
     * Set Team Position
     * @param position String Team Position
     */
    public void setPosition(String position) {
        this.position = position;
    }


    /**
     * Set Team Description
     * @param description String Team Description
     */
    public void setDescription(String description) {
        this.description = description;
    }


    /**
     * Set Team Photo
     * @param photo Image Team Photo
     */
    public void setPhoto(Image photo) {
        this.photo = photo;
    }


    /**
     * Set Team Instagram Url
     * @param instagramUrl String Team Instagram Url
     */
    public void setInstagramUrl(String instagramUrl) {
        this.instagramUrl = instagramUrl;
    }


    /**
     * Set Team Twitter Url
     * @param twitterUrl String Team Twitter Url
     */
    public void setTwitterUrl(String twitterUrl) {
        this.twitterUrl = twitterUrl;
    }


    /**
     * Set Team Facebook Url
     * @param facebookUrl String Team Facebook Url
     */
    public void setFacebookUrl(String facebookUrl) {
        this.facebookUrl = facebookUrl;
    }


    /**
     * Set Team Edit Info
     * @param editInfo EditInfo Team Edit Info
     */
    public void setEditInfo(EditInfo editInfo) {
        this.editInfo = editInfo;
    }


    /**
     * Set Team Publish Info
     * @param publishInfo PublishInfo Team Publish Info
     */
    public void setPublishInfo(PublishInfo publishInfo) {
        this.publishInfo = publishInfo;
    }


    /**
     * Set Team Order Number
     * @param orderNumber long Team Order Number
     */
    public void setOrderNumber(long orderNumber) {
        this.orderNumber = orderNumber;
    }


    /**
     * Set Multi Language Identifier
     * @return long Multi Language Identifier
     */
    public void setMultiLangKeyId(long multilangKeyId) {
        this.multilangKeyId = multilangKeyId;
    }


    /**
     * Set Multi Language Translated Languages
     * @return String Multi Language Translated Languages
     */
    public void setMultiLangKeyTranslations(String languages) {
        this.multilangKeyTranslations = languages;
    }



    // MULTI-LANGUAGE ---------------------------------------------------------


    /**
     * Gets the default non-nullable multi-language fields
     * @return
     **/
    public MultiLanguageFields[] getMultiLangKeyDefaultTranslationFields() {
        return new MultiLanguageFields[] {MultiLanguageFields.Position, MultiLanguageFields.Description};
    }


	// DAO ID -----------------------------------------------------------------

    
    /**
     * Checks if has Id Field
     */
    public boolean hasIdField() {
    	return true;
    }

    
    /**
     * Sets Id
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }


    // CACHING ----------------------------------------------------------------
    
    
	/**
	 * Gets cachePrefix
	 * @return The cachePrefix of this object
	 */
	public String getCachePrefix() {
		return CACHE_PREFIX;
	}
	
	
	/**
	 * Gets the object cache keys
	 * @return cacheKeys
	 */
	public String[] getCacheKeys() {
		if (getParameters() != null) {
			return getParameters().getCacheKeys();
		}
		return null;
	}
	

    // DATABASE MANAGER SPECIFIC ----------------------------------------------

    
    /**
     * Gets table name
     */
    public String getTableName() {
    	return "TEAM";
    }

    
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
    public String getDBConnectionName() {
    	return "Merits_Merits";
    }

    
    /**
     * Gets Insert query SQL
     * @return Insert SQL
     */
    public String getInsertSQL() {
    	// SQL
    	return "INSERT INTO TEAM (`NAME`, `PHOTO`, `INSTAGRAM_URL`, `TWITTER_URL`, `FACEBOOK_URL`, `EDIT_INFO_CREATE_DATE`, `EDIT_INFO_CREATE_USER`, `EDIT_INFO_UPDATE_DATE`, `EDIT_INFO_UPDATE_USER`, `PUBLISH_INFO_DATE`, `PUBLISH_INFO_USER`, `ORDER_NUMBER`, `MLK_ID`, `MLK_LANGS`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, (SELECT coalesce(MAX(ORDER_NUMBER) + 1,1) FROM (SELECT ORDER_NUMBER FROM TEAM) AS SUBQRY), ?, ?)";
    }

    
    /**
     * Gets Insert procedure
     */
    public String getInsertProcedureName() {
    	return "TEAM_PROC(?, ?, ?, ?, ?, ?, ?, ?, ?)";
    }


	// RESULTSETS & STATEMENTS ------------------------------------------------
	    
    
    /**
     * Fills insert fields
     * @param statement
     */
    public void fillStatementFieldsForInsert(CallableStatement statement) throws Exception {
        // Set Team Name
        statement.setString(1, StringUtilities.capString(name,100));
        // Check If Null
        if (photo == null) {
            statement.setNull(2, java.sql.Types.VARCHAR);
        } else {
            statement.setString(2, photo.serialize());
        }
        // Check If Team Instagram Url Is Null
        if (instagramUrl == null) {
            statement.setNull(3, java.sql.Types.VARCHAR);
        } else {
            // Set Team Instagram Url
            statement.setString(3, StringUtilities.capString(instagramUrl,150));
        }
        // Check If Team Twitter Url Is Null
        if (twitterUrl == null) {
            statement.setNull(4, java.sql.Types.VARCHAR);
        } else {
            // Set Team Twitter Url
            statement.setString(4, StringUtilities.capString(twitterUrl,150));
        }
        // Check If Team Facebook Url Is Null
        if (facebookUrl == null) {
            statement.setNull(5, java.sql.Types.VARCHAR);
        } else {
            // Set Team Facebook Url
            statement.setString(5, StringUtilities.capString(facebookUrl,150));
        }
        // Check if edit info create date is Null
        if (editInfo.getCreateDate() == null) {
            statement.setNull(6, java.sql.Types.TIMESTAMP);
        } else {
            // Set create date
            statement.setTimestamp(6, editInfo.getCreateDate());
        } 
        // Check if edit info create user is Null
        if (editInfo.getCreateUserId() == null) {
            statement.setNull(7, java.sql.Types.NUMERIC);
        } else {
            // Set create user
            statement.setLong(7, editInfo.getCreateUserId());
        } 
        // Check if edit info update date is Null
        if (editInfo.getUpdateDate() == null) {
            statement.setNull(8, java.sql.Types.TIMESTAMP);
        } else {
            // Set update date
            statement.setTimestamp(8, editInfo.getUpdateDate());
        } 
        // Check if edit info update user is Null
        if (editInfo.getUpdateUserId() == null) {
            statement.setNull(9, java.sql.Types.NUMERIC);
        } else {
            // Set update user
            statement.setLong(9, editInfo.getUpdateUserId());
        } 
        // Check if publish info is not null
        if (publishInfo != null) {
            // Check if publish info create date is Null
            if (publishInfo.getPublishDate() == null) {
                statement.setNull(10, java.sql.Types.TIMESTAMP);
            } else {
                // Set publish date
                statement.setTimestamp(10, publishInfo.getPublishDate());
            } 
            // Check if publish info create user is Null
                if (publishInfo.getPublishUserId() == null) {
                statement.setNull(11, java.sql.Types.NUMERIC);
            } else {
                // Set publish user
                statement.setLong(11, publishInfo.getPublishUserId());
            } 
        } else {
            statement.setNull(10, java.sql.Types.TIMESTAMP);
            statement.setNull(11, java.sql.Types.NUMERIC);
        }
        // Set Multilanguage key
        statement.setLong(12, multilangKeyId);
        // Set Multilanguage Translations
        statement.setString(13, multilangKeyTranslations);
    }


    /**
     * Sets DAO values from a resultset 
     * @param resultset
     */
    public void fillValuesFromResultSet(ResultSet resultset) throws Exception {
        // Set Team Identifier
        this.setId(resultset.getLong("ID"));
        // Set Team Name
        this.setName(resultset.getString("NAME"));
        this.setPosition(resultset.getString("POSITION"));
        this.setDescription(resultset.getString("DESCRIPTION"));
        // Set Team Photo
        this.setPhoto(Image.deserialize(resultset.getString("PHOTO")));
        // Set Team Instagram Url
        this.setInstagramUrl(resultset.getString("INSTAGRAM_URL"));
        // Check if was null
        if (resultset.wasNull()) {
            this.setInstagramUrl(null);
        }
        // Set Team Twitter Url
        this.setTwitterUrl(resultset.getString("TWITTER_URL"));
        // Check if was null
        if (resultset.wasNull()) {
            this.setTwitterUrl(null);
        }
        // Set Team Facebook Url
        this.setFacebookUrl(resultset.getString("FACEBOOK_URL"));
        // Check if was null
        if (resultset.wasNull()) {
            this.setFacebookUrl(null);
        }
        // Set Team Edit Info
        this.editInfo = new EditInfo();
        editInfo.setCreateDate(resultset.getTimestamp("EDIT_INFO_CREATE_DATE"));
        // Check if was null
        if (resultset.wasNull()) {
            editInfo.setCreateDate(null);
        }
        editInfo.setCreateUserId(resultset.getLong("EDIT_INFO_CREATE_USER"));
        // Check if was null
        if (resultset.wasNull()) {
            editInfo.setCreateUserId(null);
        }
        editInfo.setUpdateDate(resultset.getTimestamp("EDIT_INFO_UPDATE_DATE"));
        // Check if was null
        if (resultset.wasNull()) {
            editInfo.setUpdateDate(null);
        }
        editInfo.setUpdateUserId(resultset.getLong("EDIT_INFO_UPDATE_USER"));
        // Check if was null
        if (resultset.wasNull()) {
            editInfo.setUpdateUserId(null);
        }
        // Set Team Publish Info
        this.publishInfo = new PublishInfo();
        publishInfo.setPublishDate(resultset.getTimestamp("PUBLISH_INFO_DATE"));
        // Check if was null
        if (resultset.wasNull()) {
            publishInfo.setPublishDate(null);
        }
        publishInfo.setPublishUserId(resultset.getLong("PUBLISH_INFO_USER"));
        // Check if was null
        if (resultset.wasNull()) {
            publishInfo.setPublishUserId(null);
        }
        // Set Team Order Number
        this.setOrderNumber(resultset.getLong("ORDER_NUMBER"));
        // Set Team Multi Lang Key Id
        this.setMultiLangKeyId(resultset.getLong("MLK_ID"));
        // Set Team Multi Lang Key Translations
        this.setMultiLangKeyTranslations(resultset.getString("MLK_LANGS"));
        // Check if was null
        if (resultset.wasNull()) {
            this.setMultiLangKeyTranslations(null);
        }
    }

    
    // ------------------------------------------------------------------------
    // PARAMETERS CLASSES -----------------------------------------------------
    // ------------------------------------------------------------------------


}
