package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import com.weezzi.core.data.*;
import com.weezzi.core.dbmanager.dao.SingleRecordDAO;
import com.weezzi.utils.StringUtilities;
import com.weezzi.utils.extras.cache.WeezziCacheObjectType;
import com.weezzi.utils.extras.console.Console;
import com.weezzi.core.dbmanager.dao.DAOParameters;
import com.merits.modules.base.uobjects.enums.WalletType;
import com.merits.modules.base.uobjects.enums.IdcardType;


import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;



/**
 * <b>Title: </b>Wallet Data Access Object<br/>
 * <b>Description: </b>Wallet DAO Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
public class WalletsDAO extends SingleRecordDAO {


	// CONSTANTS --------------------------------------------------------------

	
	public static final String CACHE_PREFIX = "D0#";
	private static final long serialVersionUID = 1l;


    // MULTI-LANGUAGE ---------------------------------------------------------


    /**
     *  Multi-Language
     */
    public enum MultiLanguageFields {
        ;

        private String column;

        MultiLanguageFields(String column) {
        	this.column = column;
        }

        public String getColumnName() {
        	return column;
        }
	}


    // DATA TYPE ENUMERATION --------------------------------------------------


    /**
     *  DAO Search Type
     */
    public enum SearchType {

    	// Single Record Queries
        MasterWallet("Q1"),

		;
    	
        private String cachePrefix;
        
        SearchType(String cachePrefix) {
        	this.cachePrefix = cachePrefix;
        }

        /**
         * Gets cache prefix
         **/
        public String toString() {
        	return cachePrefix;
        }
    }


    // PROPERTIES --------------------------------------------------------------

    // Wallets Identifier
    private long id;
    // Wallets Wallet Type
    private WalletType walletType;
    // Wallets Card Type Identifier
    private IdcardType idcardType;
    // Wallets Card Number Identifier
    private String idcardNumber;
    // Wallets First Name
    private String firstName;
    // Wallets Last Name
    private String lastName;
    // Wallets Birthdate
    private Timestamp birthdate;
    // Wallets Country Of Origin
    private Long countryOfOrigin;


    // CONSTRUCTORS ------------------------------------------------------------


	/**
	 * Empty Constructor
	 **/
	public WalletsDAO() {
        // Set cache object type
		this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
	}


	/**
	 * Type Constructor
	 **/
	public WalletsDAO(SearchType type) {
        // Set DAO Search type
        this.setSearchType(type);
        // Set cache object type
		this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
	}
	
	
    /**
     * Wallet Bean Field Constructor
     * @param id long Wallets Identifier
     */
    public WalletsDAO(long id) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Wallets Identifier
        setId(id);
    }


    /**
     * Wallet Bean Field Constructor
     * @param id long Wallets Identifier
     * @param walletType WalletType Wallets Wallet Type
     */
    public WalletsDAO(long id, WalletType walletType) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Wallets Identifier
        setId(id);
        // Set Wallets Wallet Type
        setWalletType(walletType);
    }


    /**
     * Wallet Bean Field Constructor
     * @param id long Wallets Identifier
     * @param walletType WalletType Wallets Wallet Type
     * @param idcardType IdcardType Wallets Card Type Identifier
     * @param idcardNumber String Wallets Card Number Identifier
     * @param firstName String Wallets First Name
     * @param lastName String Wallets Last Name
     * @param birthdate Timestamp Wallets Birthdate
     * @param countryOfOrigin Long Wallets Country Of Origin
     */
    public WalletsDAO(long id, WalletType walletType, IdcardType idcardType
                    , String idcardNumber, String firstName, String lastName
                    , Timestamp birthdate, Long countryOfOrigin) {
        // Set cache object type
        this.setCacheObjectType(WeezziCacheObjectType.SingleRecord);
        // Set Wallets Identifier
        setId(id);
        // Set Wallets Wallet Type
        setWalletType(walletType);
        // Set Wallets Card Type Identifier
        setIdcardType(idcardType);
        // Set Wallets Card Number Identifier
        setIdcardNumber(idcardNumber);
        // Set Wallets First Name
        setFirstName(firstName);
        // Set Wallets Last Name
        setLastName(lastName);
        // Set Wallets Birthdate
        setBirthdate(birthdate);
        // Set Wallets Country Of Origin
        setCountryOfOrigin(countryOfOrigin);
    }


    

    
    // TYPE -------------------------------------------------------------------

    
    /**
     * Sets DAO search type
     * @param type
     */
    public void setSearchType(SearchType type) {
    	// Sets DAO type
    	super.setSearchType(type);
    }


	// GETTERS -----------------------------------------------------------------


    /**
     * Get Wallets Identifier
     * @return long Wallets Identifier
     */
    public long getId() {
        return this.id;
    }


    /**
     * Get Wallets Wallet Type
     * @return WalletType Wallets Wallet Type
     */
    public WalletType getWalletType() {
        return this.walletType;
    }


    /**
     * Get Wallets Card Type Identifier
     * @return IdcardType Wallets Card Type Identifier
     */
    public IdcardType getIdcardType() {
        return this.idcardType;
    }


    /**
     * Get Wallets Card Number Identifier
     * @return String Wallets Card Number Identifier
     */
    public String getIdcardNumber() {
        return this.idcardNumber;
    }


    /**
     * Get Wallets First Name
     * @return String Wallets First Name
     */
    public String getFirstName() {
        return this.firstName;
    }


    /**
     * Get Wallets Last Name
     * @return String Wallets Last Name
     */
    public String getLastName() {
        return this.lastName;
    }


    /**
     * Get Wallets Birthdate
     * @return Timestamp Wallets Birthdate
     */
    public Timestamp getBirthdate() {
        return this.birthdate;
    }


    /**
     * Get Wallets Country Of Origin
     * @return Long Wallets Country Of Origin
     */
    public Long getCountryOfOrigin() {
        return this.countryOfOrigin;
    }



	// SETTERS -----------------------------------------------------------------


    /**
     * Set Wallets Identifier
     * @param id long Wallets Identifier
     */
    public void setId(long id) {
        this.id = id;
    }


    /**
     * Set Wallets Wallet Type
     * @param walletType WalletType Wallets Wallet Type
     */
    public void setWalletType(WalletType walletType) {
        this.walletType = walletType;
    }


    /**
     * Set Wallets Card Type Identifier
     * @param idcardType IdcardType Wallets Card Type Identifier
     */
    public void setIdcardType(IdcardType idcardType) {
        this.idcardType = idcardType;
    }


    /**
     * Set Wallets Card Number Identifier
     * @param idcardNumber String Wallets Card Number Identifier
     */
    public void setIdcardNumber(String idcardNumber) {
        this.idcardNumber = idcardNumber;
    }


    /**
     * Set Wallets First Name
     * @param firstName String Wallets First Name
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    /**
     * Set Wallets Last Name
     * @param lastName String Wallets Last Name
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    /**
     * Set Wallets Birthdate
     * @param birthdate Timestamp Wallets Birthdate
     */
    public void setBirthdate(Timestamp birthdate) {
        this.birthdate = birthdate;
    }


    /**
     * Set Wallets Country Of Origin
     * @param countryOfOrigin Long Wallets Country Of Origin
     */
    public void setCountryOfOrigin(Long countryOfOrigin) {
        this.countryOfOrigin = countryOfOrigin;
    }



    // MULTI-LANGUAGE ---------------------------------------------------------



	// DAO ID -----------------------------------------------------------------

    
    /**
     * Checks if has Id Field
     */
    public boolean hasIdField() {
    	return true;
    }

    
    /**
     * Sets Id
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }


    // CACHING ----------------------------------------------------------------
    
    
	/**
	 * Gets cachePrefix
	 * @return The cachePrefix of this object
	 */
	public String getCachePrefix() {
		return CACHE_PREFIX;
	}
	
	
	/**
	 * Gets the object cache keys
	 * @return cacheKeys
	 */
	public String[] getCacheKeys() {
		if (getParameters() != null) {
			return getParameters().getCacheKeys();
		}
		return null;
	}
	

    // DATABASE MANAGER SPECIFIC ----------------------------------------------

    
    /**
     * Gets table name
     */
    public String getTableName() {
    	return "WALLETS";
    }

    
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
    public String getDBConnectionName() {
    	return "Merits_Merits";
    }

    
    /**
     * Gets Insert query SQL
     * @return Insert SQL
     */
    public String getInsertSQL() {
    	// SQL
    	return "INSERT INTO WALLETS (`WALLET_TYPE`, `IDCARD_TYPE`, `IDCARD_NUMBER`, `FIRST_NAME`, `LAST_NAME`, `BIRTHDATE`, `COUNTRY_OF_ORIGIN`) values (?, ?, ?, ?, ?, ?, ?)";
    }

    
    /**
     * Gets Insert procedure
     */
    public String getInsertProcedureName() {
    	return "WALLETS_PROC(?, ?, ?, ?, ?, ?, ?, ?)";
    }


	// RESULTSETS & STATEMENTS ------------------------------------------------
	    
    
    /**
     * Fills insert fields
     * @param statement
     */
    public void fillStatementFieldsForInsert(CallableStatement statement) throws Exception {
        // Set Wallets Wallet Type
        statement.setInt(1, walletType.getValue());
        // Check If Wallets Card Type Identifier Is Null
        if (idcardType == null) {
            statement.setNull(2, java.sql.Types.VARCHAR);
        } else {
            // Set Wallets Card Type Identifier
            statement.setInt(2, idcardType.getValue());
        }
        // Check If Wallets Card Number Identifier Is Null
        if (idcardNumber == null) {
            statement.setNull(3, java.sql.Types.VARCHAR);
        } else {
            // Set Wallets Card Number Identifier
            statement.setString(3, StringUtilities.capString(idcardNumber,50));
        }
        // Check If Wallets First Name Is Null
        if (firstName == null) {
            statement.setNull(4, java.sql.Types.VARCHAR);
        } else {
            // Set Wallets First Name
            statement.setString(4, StringUtilities.capString(firstName,100));
        }
        // Check If Wallets Last Name Is Null
        if (lastName == null) {
            statement.setNull(5, java.sql.Types.VARCHAR);
        } else {
            // Set Wallets Last Name
            statement.setString(5, StringUtilities.capString(lastName,100));
        }
        // Check If Wallets Birthdate Is Null
        if (birthdate == null) {
            statement.setNull(6, java.sql.Types.TIMESTAMP);
        } else {
            // Set Wallets Birthdate
            statement.setTimestamp(6, birthdate);
        }
        // Check If Wallets Country Of Origin Is Null
        if (countryOfOrigin == null) {
            statement.setNull(7, java.sql.Types.NUMERIC);
        } else {
            // Set Wallets Country Of Origin
            statement.setLong(7, countryOfOrigin);
        }
    }


    /**
     * Sets DAO values from a resultset 
     * @param resultset
     */
    public void fillValuesFromResultSet(ResultSet resultset) throws Exception {
        // Set Wallets Identifier
        this.setId(resultset.getLong("ID"));
        // Set Wallets Wallet Type
        this.setWalletType(WalletType.getByValue(resultset.getInt("WALLET_TYPE")));
        // Set Wallets Card Type Identifier
        this.setIdcardType(IdcardType.getByValue(resultset.getInt("IDCARD_TYPE")));
        // Check if was null
        if (resultset.wasNull()) {
            this.setIdcardType(null);
        }
        // Set Wallets Card Number Identifier
        this.setIdcardNumber(resultset.getString("IDCARD_NUMBER"));
        // Check if was null
        if (resultset.wasNull()) {
            this.setIdcardNumber(null);
        }
        // Set Wallets First Name
        this.setFirstName(resultset.getString("FIRST_NAME"));
        // Check if was null
        if (resultset.wasNull()) {
            this.setFirstName(null);
        }
        // Set Wallets Last Name
        this.setLastName(resultset.getString("LAST_NAME"));
        // Check if was null
        if (resultset.wasNull()) {
            this.setLastName(null);
        }
        // Set Wallets Birthdate
        this.setBirthdate(resultset.getTimestamp("BIRTHDATE", SingleRecordDAO.TIMEZONE));
        // Set Wallets Country Of Origin
        this.setCountryOfOrigin(getRSLong(resultset, "COUNTRY_OF_ORIGIN"));
    }

    
    // ------------------------------------------------------------------------
    // PARAMETERS CLASSES -----------------------------------------------------
    // ------------------------------------------------------------------------



	// MasterWallet Parameters Class -----------------------------------------------


	/**
	 * MasterWallet
	 */
	public class MasterWalletParameters extends DAOParameters {

		
		// Properties .........................................................

		
        

		// Constructors .......................................................

		
		public MasterWalletParameters() {
		}


        // DAO Parameters .....................................................


        /**
         * Gets the search fields
         * @return
         */
		public Object[] getSearchFields() {
			// Local Variables
			return new Object[] {};
		}
	
	
		/**
		 * Gets the object cache keys
		 * @return cacheKeys
		 */
		public String[] getCacheKeys() {
			return null;
		}

		
	}

}
