package com.merits.modules.base.dao;

// IMPORTS ---------------------------------------------------------------------

import java.sql.ResultSet;
import java.sql.Timestamp;
import java.sql.Timestamp;


import com.weezzi.utils.DatabaseType;
import com.weezzi.core.dbmanager.dao.DAOParameters;
import com.weezzi.core.dbmanager.dao.SpecialQueryDAO;
import com.weezzi.core.dbmanager.dao.SingleRecordDAO;
import com.weezzi.core.data.*;
import com.weezzi.utils.extras.cache.WeezziCacheObjectType;
import com.merits.modules.base.uobjects.enums.WalletType;




/**
 * <b>Title: </b>Wallet Record Data Transfer Object<br/>
 * <b>Description: </b>Wallet Record DTO Class<br/>
 * <b>Copyright: </b>Copyright (c) 2020 Overture Software<br/>
 * <b>Company: </b><A HREF="http://www.overturesoftware.com">Overture Software</A><br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */
@SuppressWarnings("unused")
public class WalletRecordsTotalsSPQ extends SpecialQueryDAO {


	// CONSTANTS ---------------------------------------------------------------

	
	public static final String CACHE_PREFIX = "S1_1#";
	private static final long serialVersionUID = 1L;


    // PROPERTIES -------------------------------------------------------------


	// Special Query Fields	
    // Totals Wallet Type
    private WalletType walletType;
    // Totals Total Value
    private float totalValue;


    // CONSTRUCTORS -----------------------------------------------------------


	/**
	 * Empty Constructor
	 **/
	public WalletRecordsTotalsSPQ() {
        // Set cache object type
		this.setCacheObjectType(WeezziCacheObjectType.SpecialQuery);
	}
	
	// SPECIAL QUERY METHODS --------------------------------------------------


    /**
     * Wallet Record Bean Field Constructor
     * @param walletType WalletType Wallet Records Wallet Type
     * @param totalValue float Wallet Records Total Value
     */
    public WalletRecordsTotalsSPQ(WalletType walletType, float totalValue) {
        // Call default constructor
        this();
        // Set Wallet Records Wallet Type
        setWalletType(walletType);
        // Set Wallet Records Total Value
        setTotalValue(totalValue);
    }


    // GETTERS -----------------------------------------------------------------


    /**
     * Get Wallet Records Wallet Type
     * @return WalletType Wallet Records Wallet Type
     */
    public WalletType getWalletType() {
        return this.walletType;
    }


    /**
     * Get Wallet Records Total Value
     * @return float Wallet Records Total Value
     */
    public float getTotalValue() {
        return this.totalValue;
    }


    // SETTERS -----------------------------------------------------------------


    /**
     * Set Wallet Records Wallet Type
     * @param walletType WalletType Wallet Records Wallet Type
     */
    public void setWalletType(WalletType walletType) {
        this.walletType = walletType;
    }


    /**
     * Set Wallet Records Total Value
     * @param totalValue float Wallet Records Total Value
     */
    public void setTotalValue(float totalValue) {
        this.totalValue = totalValue;
    }


   


    // CACHING ----------------------------------------------------------------
    
    
	/**
	 * Gets cachePrefix
	 * @return The cachePrefix of this object
	 */
	public String getCachePrefix() {
		return CACHE_PREFIX;
	}

    // DATABASE MANAGER SPECIFIC ----------------------------------------------

    
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
    public String getDBConnectionName() {
    	return "Merits_Merits";
    }


    public void fillValuesFromResultSet(ResultSet resultset) throws Exception {
        // Set Wallet Records Wallet Type
        this.setWalletType(WalletType.getByValue(resultset.getInt("WALLET_TYPE")));
        // Set Wallet Records Total Value
        this.setTotalValue(resultset.getFloat("TOTAL_VALUE"));
    }

	
	// SPECIAL QUERY PARAMETERS OBJECT CLASS ----------------------------------
	
	
	/**
	 * Wallet Record 
	 */
	public class Parameters extends DAOParameters {

		
		// Properties .........................................................

		

		
		// Constructors .......................................................


    public Parameters() {
    }



        // DAO Parameters .....................................................


        /**
         * Gets the search fields
         * @return
         */
		public Object[] getSearchFields() {
			// Local Variables
			return new Object[] {};
		}
	
	
		/**
		 * Gets the object cache keys
		 * @return cacheKeys
		 */
		public String[] getCacheKeys() {
			return null;
		}
		
	}
}
