package com.merits.modules.base.site.components;

//IMPORTS -------------------------------------------------------------------------

import com.merits.modules.base.site.components.definitions.CashiersPaymentStatusDefinition;
import com.weezzi.webserver.simel.AttributeMapper;
import com.weezzi.webserver.simel.Expression;


/**
 * <b>Title: </b> CashiersPaymentStatus<br/>
 * <b>Description: </b> <br/>
 *
 * @author Auto-generated by Weezzi Site Builder
 * @version 1.0
 */
public class CashiersPaymentStatus extends CashiersPaymentStatusDefinition {


	// CONSTANTS ---------------------------------------------------------------

	
	// INITIALIZATION ----------------------------------------------------------
	
	
	public void customComponentInitialization() {
	};


	// BROWSER OUTPUT ----------------------------------------------------------


	/**
	 * Generate Start Output
	 * @return String
	 */
	public String getStartOutput() {
		// Local Variables
		Expression expr;
		AttributeMapper map;
		// Get Expression
		expr = getHTMLExpression("Default");
		map = expr.getAttributeMapper();
		// Add attributes
		switch(getParameterAsInteger("Status")) {
			case 1:
				map.addAttribute("TITLE", getGlobalDictionaryTranslation("Payment_Successful"));
				map.addAttribute("STYLE", getObfuscatedStyle("PaymentResultOk"));
				map.addAttribute("GLOW_STYLE", getObfuscatedStyle("glowOk"));
				map.addAttribute("ICON", getObfuscatedStyle("PaymentResultIconOk"));
				break;
			case 2:
				map.addAttribute("TITLE", getGlobalDictionaryTranslation("Payment_Refused"));
				map.addAttribute("STYLE", getObfuscatedStyle("PaymentResultRefused"));
				map.addAttribute("GLOW_STYLE", getObfuscatedStyle("glowRefused"));
				map.addAttribute("ICON", getObfuscatedStyle("PaymentResultIconRefused"));
				break;
			case 3:
				map.addAttribute("TITLE", getGlobalDictionaryTranslation("Payment_NoBalance"));
				map.addAttribute("STYLE", getObfuscatedStyle("PaymentResultNoBalance"));
				map.addAttribute("GLOW_STYLE", getObfuscatedStyle("glowNoBalance"));
				map.addAttribute("ICON", getObfuscatedStyle("PaymentResultIconNoBalance"));
				break;
			case 4:
				map.addAttribute("TITLE", getGlobalDictionaryTranslation("Payment_Error"));
				map.addAttribute("STYLE", getObfuscatedStyle("PaymentResultNoBalance"));
				map.addAttribute("GLOW_STYLE", getObfuscatedStyle("glowNoBalance"));
				map.addAttribute("ICON", getObfuscatedStyle("PaymentResultIconNoBalance"));
				break;
		}
		// Render
		return expr.render(map);
	}

	
	// PRIVATE ----------------------------------------------------------------


}

