package com.merits.modules.base.site.components;

//IMPORTS -------------------------------------------------------------------------

import com.merits.modules.base.site.components.definitions.HomeHeaderDefinition;
import com.weezzi.webserver.simel.AttributeMapper;
import com.weezzi.webserver.simel.Expression;


/**
 * <b>Title: </b> HomeHeader<br/>
 * <b>Description: </b> <br/>
 *
 * @author Auto-generated by Weezzi Site Builder
 * @version 1.0
 */
public class HomeHeader extends HomeHeaderDefinition {


	// CONSTANTS ---------------------------------------------------------------

	
	// INITIALIZATION ----------------------------------------------------------
	
	
	public void customComponentInitialization() {
		addGlobalScript("Scripts");
	};


	// BROWSER OUTPUT ----------------------------------------------------------


	/**
	 * Generate Start Output
	 * @return String
	 */
	public String getStartOutput() {
		// Local Variables
		Expression expr;
		AttributeMapper map;
		// Get Expression
		expr = getHTMLExpression("Default");
		String selectedStyle = getObfuscatedStyle("Selected");
		map = expr.getAttributeMapper();
		setDefaultMapProperties(map, getPropertiesDefinition());
		// Add attributes
		map.addAttribute("IT_LINK", getPageLink(getPageName(), "it"));
		map.addAttribute("EN_LINK", getPageLink(getPageName(), "en"));
		if (getSiteLanguage().equals("it")) {
			map.addAttribute("IT_CLASS", selectedStyle);	
		} else {
			map.addAttribute("EN_CLASS", selectedStyle);	
		}
		// Render
		return expr.render(map);
	}

	
	// PRIVATE ----------------------------------------------------------------


}

