package com.merits.modules.base.site.components;

import com.merits.core.MeritsUtils;
import com.merits.modules.base.container.BaseContainer;
import com.merits.modules.base.dao.BulkShopCashiersDAO;
import com.merits.modules.base.dao.ShopCashiersDAO;

//IMPORTS -------------------------------------------------------------------------

import com.merits.modules.base.site.components.definitions.ShopCashiersDefinition;
import com.weezzi.utils.extras.console.Console;
import com.weezzi.webserver.simel.AttributeMapper;
import com.weezzi.webserver.simel.Expression;


/**
 * <b>Title: </b> ShopCashiers<br/>
 * <b>Description: </b> <br/>
 *
 * @author Auto-generated by Weezzi Site Builder
 * @version 1.0
 */
public class ShopCashiers extends ShopCashiersDefinition {


	// CONSTANTS ---------------------------------------------------------------

	
	// INITIALIZATION ----------------------------------------------------------
	
	
	public void customComponentInitialization() {
	};


	// BROWSER OUTPUT ----------------------------------------------------------


	/**
	 * Generate Start Output
	 * @return String
	 */
	public String getStartOutput() {
		// Local Variables
		Expression expr;
		AttributeMapper map;
		// Get Expression
		expr = getHTMLExpression("Default");
		map = expr.getAttributeMapper();
		// Add attributes
		map.addAttribute("CASHIERS", renderCashiers());
		// Render
		return expr.render(map);
	}

	
	// PRIVATE ----------------------------------------------------------------


	/**
	 * @return
	 */
	private String renderCashiers() {
		// Local Variables
		Expression expr;
		AttributeMapper map;
		BulkShopCashiersDAO records;
		StringBuilder buffer = new StringBuilder();
		// Get Expression
		expr = getHTMLExpression("Cashier");
		map = expr.getAttributeMapper();
		try {
			records = BaseContainer.getShopCashiersFindByAll(getSiteUserId());
		} catch (Exception e) {
			// Catch Exception
			Console.error("Error getting cashiers for shop \"" + getSiteUserId() + "\" records", e);;
			return "";
		}
		// Render records
		for(ShopCashiersDAO rec : records.data) {
			map.addAttribute("ID", encryptData(rec.getId()));
			map.addAttribute("NAME", MeritsUtils.getPersonName(rec.getFirstName(), rec.getLastName()));
			buffer.append(expr.render(map));
		}
		// Check if no cashiers yet
		if (buffer.length() == 0) {
			buffer.append(getHTML("NoCashiers"));
		}
		// Render
		return buffer.toString();
	}

}

