package com.merits.modules.base.site.components;

import com.merits.core.MeritsUtils;
import com.merits.modules.base.container.BaseContainer;
import com.merits.modules.base.dao.PaymentsRequestsDAO;
import com.merits.modules.base.dao.ShopsDAO;

//IMPORTS -------------------------------------------------------------------------

import com.merits.modules.base.site.components.definitions.VolunteersPaymentRequestDefinition;
import com.weezzi.utils.extras.console.Console;
import com.weezzi.webserver.simel.AttributeMapper;
import com.weezzi.webserver.simel.Expression;


/**
 * <b>Title: </b> VolunteersPaymentRequest<br/>
 * <b>Description: </b> <br/>
 *
 * @author Auto-generated by Weezzi Site Builder
 * @version 1.0
 */
public class VolunteersPaymentRequest extends VolunteersPaymentRequestDefinition {


	// CONSTANTS ---------------------------------------------------------------

	
	// INITIALIZATION ----------------------------------------------------------
	
	
	public void customComponentInitialization() {
		addScript("LocalScripts");
	};


	// BROWSER OUTPUT ----------------------------------------------------------


	/**
	 * Generate Start Output
	 * @return String
	 */
	public String getStartOutput() {
		// Local Variables
		String[] value;
		Expression expr;
		AttributeMapper map;
		PaymentsRequestsDAO pr;
		ShopsDAO shop;
		// Get Expression
		expr = getHTMLExpression("Default");
		map = expr.getAttributeMapper();
		// Get request
		try {
			pr = BaseContainer.getPaymentsRequest(getParameterEncryptedAsLong("Id"));
			if (pr == null) {
				sendRedirect(getPageLink("Volunteers_Home"));
				return "";
			}
			map.addAttribute("ID", getParameter("Id"));
			value = MeritsUtils.getWalletValue(pr.getTransactionValue());
			shop = BaseContainer.getShop(pr.getIdShop());
			map.addAttribute("NAME", shop.getName());
			if (shop.getPhoto() != null) {
				map.addAttribute("PHOTO", getImage(shop.getPhoto(), 500, 500));
			}
			map.addAttribute("VALUE_INT", value[0]);
			map.addAttribute("VALUE_DEC", value[1]);
		} catch (Exception e) {
			Console.error("Error getting payment request", e);
		}
		// Add attributes
		// Render
		return expr.render(map);
	}

	
	// PRIVATE ----------------------------------------------------------------


}

