package com.merits.modules.base.site.components;

import com.merits.core.MeritsUtils;
import com.merits.core.WalletTransactionInfo;
import com.merits.modules.base.container.BaseContainer;
import com.merits.modules.base.dao.GoodTypesDAO;
import com.merits.modules.base.dao.ShopTransactionsDAO;
import com.merits.modules.base.dao.WalletRecordsDAO;

//IMPORTS -------------------------------------------------------------------------

import com.merits.modules.base.site.components.definitions.VolunteersPaymentsDetailsDefinition;
import com.merits.modules.base.uobjects.enums.WalletType;
import com.weezzi.utils.extras.console.Console;
import com.weezzi.webserver.simel.AttributeMapper;
import com.weezzi.webserver.simel.Expression;


/**
 * <b>Title: </b> VolunteersPaymentsDetails<br/>
 * <b>Description: </b> <br/>
 *
 * @author Auto-generated by Weezzi Site Builder
 * @version 1.0
 */
public class VolunteersPaymentsDetails extends VolunteersPaymentsDetailsDefinition {


	// CONSTANTS ---------------------------------------------------------------

	
	// INITIALIZATION ----------------------------------------------------------
	
	
	public void customComponentInitialization() {
	};


	// BROWSER OUTPUT ----------------------------------------------------------


	/**
	 * Generate Start Output
	 * @return String
	 */
	public String getStartOutput() {
		// Local Variables
		Long id = null;
		long walletId;
		Expression expr;
		AttributeMapper map;
		WalletTransactionInfo info;
		WalletRecordsDAO rec;
		ShopTransactionsDAO shopTransaction;
		StringBuilder goods = null;
		String[] goodTypes;
		GoodTypesDAO goodType;
		// Get id
		try {
			id = getParameterEncryptedAsLong("PID");
			rec = BaseContainer.getWalletRecordFindByTransaction(id, MeritsUtils.getWalletId(getContext()));
		} catch (Exception e) {
		}
		if (id == null) {
			sendRedirect(getPageLink("Volunteers_Payments"));
			return "";
		}
		// Get record
		try {
			walletId = MeritsUtils.getWalletId(getContext());
			rec = BaseContainer.getWalletRecordFindByTransaction(id, walletId);
			if (rec == null) {
				Console.warning("Volunteer wallet record not found " + id + " for wallet id " + walletId);
				sendRedirect(getPageLink("Volunteers_Payments"));
				return "";
			}
			if (rec.getRefWalletType() == WalletType.Shop) {
				shopTransaction = BaseContainer.getShopTransactionFindByVolunteerWallet(rec.getId());
				if (shopTransaction == null) {
					Console.warning("Shop transation not found for volunteer wallet record " + rec.getId());
					sendRedirect(getPageLink("Volunteers_Payments"));
					return "";
				}
				goods = new StringBuilder();
				if (shopTransaction.getGoodTypes() != null) {
					goodTypes = shopTransaction.getGoodTypes().split("[,]");
					for(String gt : goodTypes) {
						goodType = BaseContainer.getGoodType(Long.parseLong(gt), getSiteLanguage());
						if (goods.length() > 0) {
							goods.append(", ");
						}
						goods.append(goodType.getName());
					}
				}
			}
			
			// Get Info
			info = MeritsUtils.getReferenceTransactionInfo(getContext(), rec, getSiteLanguage());
		} catch (Exception e) {
			Console.error("Getting record", e);
			sendRedirect(getPageLink("Volunteers_Payments"));
			return "";
		}
		// Get Expression
		expr = getHTMLExpression("Default");
		map = expr.getAttributeMapper();
		// Add attributes
		map.addAttribute("NAME", info.getName());
		map.addAttribute("DATE", info.getDate());
		map.addAttribute("PHOTO", info.getPhoto());
		map.addAttribute("VALUE_INT", info.getValueInteger());
		map.addAttribute("VALUE_DEC", info.getValueDecimal());
		if (rec.getRefWalletType() == WalletType.Shop) {
			map.addAttribute("GOODS", goods);
		}
		// Render
		return expr.render(map);
	}

	
	// PRIVATE ----------------------------------------------------------------


}

