package com.merits.modules.base.backoffice.tables;

import com.merits.core.MeritsUtils;

//IMPORTS -------------------------------------------------------------------------

import com.merits.modules.base.backoffice.tables.definitions.ShopsTableDefinition;
import com.merits.modules.base.container.BaseContainer;
import com.merits.modules.base.dao.BulkShopCashiersDAO;
import com.merits.modules.base.dao.BulkShopsDAO;
import com.merits.modules.base.dao.ShopCashiersDAO;
import com.merits.modules.base.dao.ShopsDAO;
import com.merits.modules.base.dao.WalletRecordsGetBalanceSPQ;
import java.util.Collection;
import java.util.Vector;

import com.weezzi.core.context.TableContext;
import com.weezzi.core.data.Tree;
import com.weezzi.webserver.simel.AttributeMapper;
import com.weezzi.webserver.simel.Expression;
import com.weezzi.core.tables.TableColumnOrdering;
import com.weezzi.utils.extras.console.Console;


/**
 * <b>Title: </b> Shops<br/>
 * <b>Description: </b> <br/>
 *
 * @author Auto-generated by Weezzi Builder
 * @version 1.0
 */
@SuppressWarnings("unused")
public class ShopsTable extends ShopsTableDefinition {



	// TABLE SPECIFIC ---------------------------------------------------------


	/**
	 * Initializes the table
	 */
	public void initializeTable() {
		// Local Variables
		
	}

	/**
	 * Wraps up table finalization
	 */
	public void finalizeTable() {
		// Local Variables
		
	}
	
	
	// ACTIONS ----------------------------------------------------------------
	
	
	/**
	 * Add Action
	 * @param context
	 */
	public void doAddAction(TableContext context, String categoryId) {
		// Local Variables
		showFormDialog("AddShop", null);
	}


	/**
	 * Remove Action
	 * @param context
	 * @param ids Remove row ids 
	 */
	public void doRemoveAction(TableContext context, Collection<Long> ids) {
		// Local Variables
		long shopId;
		BulkShopCashiersDAO cashiers;
		for(Long id : ids ) {
			try {
				shopId = id;
				BaseContainer.removeShop(shopId);
				cashiers = BaseContainer.getShopCashiersFindByAll(shopId);
				for(ShopCashiersDAO cashier : cashiers.data) {
					BaseContainer.removeShopCashier(cashier.getId());
				}
			} catch (Exception e) {
				Console.error("Error deleting shop", e);
			}
		}

	}


	/**
	 * Move Action
	 * @param context
	 * @param sourceId Source Id
	 * @param destinationId Destination Id
	 */
	public void doMoveAction(TableContext context, String sourceId, String destinationId, String direction) {
		// Local Variables
		
	}

	
	/**
	 * Publish Action
	 * @param context
	 * @param id Source Id
	 * @param published Published
	 */
	public boolean doPublishAction(TableContext context, String id, boolean published) {
		// Local Variables
		return false;
	}

	
	// RENDERS ----------------------------------------------------------------
	
	
	/**
	 * Gets data action
	 */
	public void doGetDataAction(TableContext context, int startIndex, int endIndex, String search, String categoryId) {
		// Local Variables
		String name;
		WalletRecordsGetBalanceSPQ balance;
		BulkShopsDAO shops = BaseContainer.getShopsBlockFindByGetAll(search, startIndex, endIndex);
		for(ShopsDAO shop : shops.data) {
			name = "";
			if (shop.getOwnerFirstName() != null) {
				name += shop.getOwnerFirstName();
			}
			if (shop.getOwnerLastName() != null) {
				name += " " + shop.getOwnerLastName();
			}
			try {
				balance = BaseContainer.getWalletRecordsFindByGetBalanceSPQ(shop.getIdWallet());
				addRow( 
						shop.getId(), 
						shop.getPhoto(), 
						shop.getName(), 
						name, 
						MeritsUtils.formatNumber(balance.getBalance()) + " merits", 
						"Redeem", 
						null, 
						"redeemShop(\"" + encryptData(shop.getId()) + "\")", 
						shop.getEditInfo());
			} catch (Exception e) {
				// Catch Exception
				Console.error("Error getting shop balance", e);
			}
		}
	}

	
	/**
	 * Renders a tree
	 */
	public Tree doGetTreeAction(TableContext context) {
		// Local Variables
		return null;
	}

}

