package com.merits.modules.base.lists;

// IMPORTS ---------------------------------------------------------------------

import com.weezzi.core.dbmanager.dao.ListDAO;
import com.weezzi.core.dbmanager.dao.DAOParameters;


/**
 * <b>Title: </b>Volunteers Volunteers List<br/>
 * <b>Description: </b>Volunteers Volunteers List List Class<br/>
 *
 * @author AUTO-GENERATED By Weezzi Builder
 * @version 1.0
 */

public class VolunteersListVolunteers extends ListDAO {


    // CONSTANTS --------------------------------------------------------------


	private static final long serialVersionUID = 1L;


    // PROPERTIES -------------------------------------------------------------


    // CONSTRUCTORS -----------------------------------------------------------


	/**
	 * List Constructor
	 **/
	public VolunteersListVolunteers() {
		super();
	}
	

    // CACHING ----------------------------------------------------------------
    
    
	/**
	 * Gets cachePrefix
	 * @return The cachePrefix of this object
	 */
	public String getCachePrefix() {
		return "L3_0";
	}


    // DATABASE MANAGER SPECIFIC ----------------------------------------------

    
    /**
     * Gets DB Connection name
     * @return project database connection name;
     */
    public String getDBConnectionName() {
    	return "Merits_Merits";
    }
	
	
	// LIST PARAMETERS CLASS ---------------------------------------------------
	
	
	/**
	 * Volunteers Volunteers List 
	 */
	public class Parameters extends DAOParameters {

		
		// Properties .........................................................

		

		
		// Constructors .......................................................

		
		public Parameters() {

		}


        // DAO Parameters .....................................................


        /**
         * Gets the search fields
         * @return
         */
		public Object[] getSearchFields() {
			// Local Variables
			return new Object[] {};
		}
	
	
		/**
		 * Gets the object cache keys
		 * @return cacheKeys
		 */
		public String[] getCacheKeys() {
			return null;
		}
		
	}	
}
